'use client'
import {useEffect,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {paymentError} from '@/app/components/PlatformImage'
import s from '@/app/components/game-room.module.css'
type Message={id:string;sender_id:string;body:string;created_at:string}
export default function SupportConversation({thread,uid}:{thread:string;uid:string}){
 const [messages,setMessages]=useState<Message[]>([]),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[limit,setLimit]=useState(100),[version,setVersion]=useState(0)
 const pending=useRef<{id:string;body:string}|null>(null),lock=useRef(false),scroll=useRef<HTMLDivElement>(null),last=useRef('')
 useEffect(()=>{let active=true;async function load(){const r=await createClient().from('support_messages').select('id,sender_id,body,created_at').eq('thread_user_id',thread).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(limit);if(active){if(r.error)setError(r.error.message);else setMessages((r.data??[]).reverse())}}void load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},10000);return()=>{active=false;window.clearInterval(timer)}},[thread,version,limit])
 useEffect(()=>{const latest=messages.at(-1)?.id??'',el=scroll.current;if(el&&latest!==last.current){if(!last.current||el.scrollHeight-el.scrollTop-el.clientHeight<150||messages.at(-1)?.sender_id===uid)el.scrollTop=el.scrollHeight;last.current=latest}},[messages,uid])
 async function send(){if(lock.current||!body.trim())return;lock.current=true;setBusy(true);setError('');try{if(!pending.current||pending.current.body!==body.trim())pending.current={id:crypto.randomUUID(),body:body.trim()};const r=await createClient().rpc('openly_support_send',{p_id:pending.current.id,p_thread:thread,p_body:pending.current.body});if(r.error)throw r.error;pending.current=null;setBody('');setVersion(v=>v+1)}catch(e){setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 return <div className={s.room}><section className={s.chatShell}><header className={s.chatHeader}><span className={s.chatLogo}>o.</span><div><strong>Openly Support</strong><span>Private · User & admin team</span></div></header>{error&&<p className={s.error} role="alert">{error}</p>}<div className={s.chatMessages} ref={scroll} role="log" aria-label="Support conversation">{messages.length===limit&&<button className={s.secondary} onClick={()=>setLimit(n=>n+100)}>Load earlier messages</button>}{!messages.length&&<div className={s.chatEmpty}><h3>How can we help?</h3><p>Send a message below. Check back here for the admin’s reply.</p></div>}{messages.map(m=><div key={m.id} className={`${s.messageRow} ${m.sender_id===uid?s.messageMine:''}`}><div className={s.messageGroup}><span className={s.sender}>{m.sender_id===uid?'You':m.sender_id===thread?'Customer':'Openly Support'}</span><p className={s.bubble}>{m.body}</p><time className={s.messageTime}>{new Date(m.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time></div></div>)}</div><form className={s.composer} onSubmit={e=>{e.preventDefault();void send()}}><textarea aria-label="Support message" placeholder="Message Openly…" value={body} maxLength={4000} disabled={busy} onChange={e=>setBody(e.target.value)}/><button className={s.sendButton} disabled={busy||!body.trim()} aria-label="Send support message">↑</button></form><p className={s.chatFootnote}>Refreshes every 10 seconds · Replies appear here</p></section></div>
}
