'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {paymentError} from '@/app/components/PlatformImage'
import {paymentMethodName} from '@/app/plus/types'
import {Review,type ReviewOrder} from '@/app/admin/payments/PaymentReview'
import s from '@/app/components/platform.module.css'
type Transaction=ReviewOrder&{approved_at:string|null;review:{display_name:string|null;reviewed_at:string}|null}
type Report={rows:Transaction[];count:number;summary:{received:number;approved_count:number;plus:number;session:number;pending:number;gcash:number;maribank:number;other:number}}
const money=(n:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(n)
const date=(value:string)=>new Date(value).toLocaleString('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'short'})
const labels:Record<string,string>={all:'All statuses',approved:'Approved',pending_review:'Awaiting review',awaiting_payment:'Awaiting payment',rejected:'Rejected',cancelled:'Cancelled'}
export default function Transactions(){
 const [report,setReport]=useState<Report|null>(null),[status,setStatus]=useState('all'),[method,setMethod]=useState('all'),[page,setPage]=useState(0),[version,setVersion]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[uid,setUid]=useState(''),[selected,setSelected]=useState<Transaction|null>(null)
 useEffect(()=>{let live=true;void(async()=>{setLoading(true);setError('');try{const db=createClient();const [auth,result]=await Promise.all([db.auth.getUser(),db.rpc('openly_admin_transactions',{p_page:page,p_status:status,p_method:method})]);if(auth.error)throw auth.error;if(result.error)throw result.error;if(live){setReport(result.data);setUid(auth.data.user?.id??'')}}catch(e){if(live){setError(paymentError(e));setReport(null)}}finally{if(live)setLoading(false)}})();return()=>{live=false}},[page,status,method,version])
 const summary=report?.summary
 return <><span className={s.kicker}>OPENLY ADMIN</span><h1>Overall transactions</h1><p>All Openly Plus and session-unlock purchases. Received totals include approved payments only; they do not include players paying their hosts.</p>
 {error&&<p className={s.error} role="alert">{error}</p>}
 {summary&&<><div className={s.transactionStats}><section><span>Total received</span><strong>{money(summary.received)}</strong><small>{summary.approved_count} approved payments · all time</small></section><section><span>Openly Plus</span><strong>{money(summary.plus)}</strong><small>Approved monthly purchases</small></section><section><span>Session unlocks</span><strong>{money(summary.session)}</strong><small>Approved one-game purchases</small></section><section><span>Awaiting review</span><strong>{summary.pending}</strong><small>Not included in received totals</small></section></div><p className={s.muted}>All-time received: GCash {money(summary.gcash)} · MariBank {money(summary.maribank)}{Number(summary.other)>0?` · Other methods ${money(summary.other)}`:''}. These totals reflect manual verification, not bank balances or refunds.</p></>}
 <div className={s.paymentToolbar}><label>Status<select aria-label="Status" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);setSelected(null)}}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Payment method<select aria-label="Payment method" value={method} onChange={e=>{setMethod(e.target.value);setPage(0);setSelected(null)}}><option value="all">All methods</option>{['paymongo','gcash','maribank','maya','bank_transfer'].map(m=><option key={m} value={m}>{paymentMethodName(m)}</option>)}</select></label><button className={s.secondary} disabled={loading} onClick={()=>{setSelected(null);setVersion(v=>v+1)}}>Refresh transactions</button></div>
 {selected&&<Review key={`${selected.id}-${version}`} order={selected} uid={uid} onClose={()=>setSelected(null)} onReviewed={()=>{setSelected(null);setVersion(v=>v+1)}}/>}
 {loading?<p role="status">Loading transactions…</p>:report&&<><p className={s.muted}>{report.count} matching purchases · dates shown in Philippine time. Summary totals above cover all purchases.</p>{report.rows.length?<div className={s.transactionTable}><table><caption className={s.muted}>Purchase history</caption><thead><tr><th>Host / purchase</th><th>Payment method</th><th>Amount</th><th>Status</th><th>Dates / verified by</th><th>Details</th></tr></thead><tbody>{report.rows.map(o=><tr key={o.id}><td><strong>{o.host?.display_name??'Host'}</strong><p>{o.product==='openly_plus_monthly'?'Openly Plus':'Session unlock'}{o.game?` · ${o.game.title}`:''}</p><small>{o.id}</small></td><td>{paymentMethodName(o.payment_snapshot.provider)}<p>{o.payment_snapshot.account_name}</p><small>Reference: {o.payment_reference??'Not submitted'}</small></td><td className={s.amount}>{money(o.amount)}</td><td><span className={s.pill}>{labels[o.status]}</span></td><td><small>Created: {date(o.created_at)}</small>{o.approved_at&&<p>Approved: {date(o.approved_at)}</p>}{o.review&&<small>Reviewed by {o.review.display_name??'Admin'}<br/>{date(o.review.reviewed_at)}</small>}</td><td><button className={s.secondary} onClick={()=>setSelected(o)}>View payment</button></td></tr>)}</tbody></table></div>:<p className={s.empty}>No transactions match these filters.</p>}<div className={s.actions}><button className={s.secondary} disabled={page===0} onClick={()=>{setSelected(null);setPage(p=>p-1)}}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(report.count/20))}</span><button className={s.secondary} disabled={(page+1)*20>=report.count} onClick={()=>{setSelected(null);setPage(p=>p+1)}}>Next</button></div></>}
 </>
}
