'use client'
import {useEffect,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import s from '@/app/components/platform.module.css'
type Game={id:string;title:string;status:string;starts_at:string;host:{display_name:string}|null}
export default function GameDirectory(){const [rows,setRows]=useState<Game[]>([]),[status,setStatus]=useState('published'),[page,setPage]=useState(0),[version,setVersion]=useState(0),[selected,setSelected]=useState<Game|null>(null),[reason,setReason]=useState(''),[agree,setAgree]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false)
 useEffect(()=>{let active=true;async function load(){let q=createClient().from('open_plays').select('id,title,status,starts_at,host:profiles!host_id(display_name)').order('created_at',{ascending:false}).order('id').range(page*20,page*20+20);if(status!=='all')q=q.eq('status',status);const r=await q;if(active){if(r.error)setError(r.error.message);else setRows((r.data??[]).map(g=>({...g,host:Array.isArray(g.host)?g.host[0]:g.host})))}}void load();return()=>{active=false}},[status,page,version])
 async function cancel(){if(!selected||lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await createClient().rpc('openly_cancel_event',{p_event:selected.id,p_reason:reason});if(r.error)throw r.error;setNotice('Open Play cancelled. Registrations were cancelled; arrange any refunds with the host.');setSelected(null);setVersion(v=>v+1)}catch(e){setError(e&&typeof e==='object'&&'message'in e?String(e.message):'Please retry.')}finally{lock.current=false;setBusy(false)}}
 return <><span className={s.kicker}>OPENLY ADMIN</span><h1>Manage Open Plays</h1><label>Game status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}>{['published','draft','cancelled','completed','all'].map(v=><option key={v}>{v}</option>)}</select></label>{error&&<p className={s.error} role="alert">{error}</p>}{notice&&<p className={s.notice} role="status">{notice}</p>}{selected&&<section className={s.card}><h2>Cancel “{selected.title}”?</h2><p>Players lose their registrations. This does not refund transfers already sent to the host or Openly, and does not restore the host’s daily allowance.</p><label>Cancellation reason<textarea required maxLength={1000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={agree} disabled={busy} onChange={e=>setAgree(e.target.checked)}/>I understand and want to cancel this Open Play.</label><div className={s.actions}><button className={s.primary} disabled={busy||!agree||!reason.trim()} onClick={()=>void cancel()}>Confirm cancellation</button><button className={s.secondary} disabled={busy} onClick={()=>setSelected(null)}>Keep game</button></div></section>}<div className={s.tableList}>{rows.slice(0,20).map(g=><article key={g.id} className={s.card}><div className={s.receiptHeading}><h3>{g.title}</h3><span className={s.pill}>{g.status}</span></div><p>{g.host?.display_name??'Host'} · {new Date(g.starts_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p><div className={s.actions}>{g.status!=='draft'&&<a className={s.secondary} href={`/?join=${g.id}`}>Open game</a>}{['draft','published'].includes(g.status)&&<button className={s.secondary} onClick={()=>{setSelected(g);setReason('');setAgree(false);setNotice('')}}>Cancel Open Play</button>}</div></article>)}</div>{!rows.length&&<p className={s.empty}>No games in this view.</p>}<div className={s.actions}><button className={s.secondary} disabled={page===0} onClick={()=>setPage(v=>v-1)}>Previous</button><span>Page {page+1}</span><button className={s.secondary} disabled={rows.length<=20} onClick={()=>setPage(v=>v+1)}>Next</button></div></>}
