'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { safeNextPath } from '@/lib/auth/next-path'
import styles from '@/app/auth.module.css'

const friendlyError=(message?:string)=>{const value=(message??'').toLowerCase();if(value.includes('invalid login'))return'Email or password is incorrect.';if(value.includes('email not confirmed'))return'Confirm your email before logging in.';if(value.includes('rate limit')||value.includes('too many'))return'Too many attempts. Please wait and try again.';if(value.includes('different from the old password')||value.includes('different from old password')||value.includes('same password'))return'Your new password must be different from your current password.';if(value.includes('password'))return'Use at least 8 characters with a letter and a number.';return'Something went wrong. Please try again.'}

export function EmailLoginForm({nextPath}:{nextPath:string}){const router=useRouter(),next=safeNextPath(nextPath);const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');const db=createClient(),result=await db.auth.signInWithPassword({email:email.trim(),password});if(result.error||!result.data.user){setError(friendlyError(result.error?.message));setBusy(false);return}const profile=await db.from('profiles').select('onboarding_completed_at').eq('id',result.data.user.id).single();if(profile.error){setError('Your account opened, but your player profile could not be loaded.');setBusy(false);return}router.replace(profile.data.onboarding_completed_at?next:`/onboarding?next=${encodeURIComponent(next)}`);router.refresh()}return <form className={styles.form} onSubmit={submit}><label className={styles.field}>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className={styles.field}>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><div className={styles.row}><span/><a href="/forgot-password">Forgot password?</a></div><button className={styles.button} disabled={busy}>{busy?'Logging in…':'Log in'}</button>{error&&<p role="alert" className={styles.error}>{error}</p>}</form>}

export function SignUpForm({nextPath}:{nextPath:string}){const router=useRouter(),next=safeNextPath(nextPath);const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[agreed,setAgreed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);async function submit(event:FormEvent){event.preventDefault();setError('');if(password.length<8){setError('Password must be at least 8 characters.');return}if(!/[A-Za-z]/.test(password)||!/[0-9]/.test(password)){setError('Password must contain a letter and a number.');return}if(password!==confirm){setError('Passwords do not match.');return}if(!agreed){setError('Please accept the Privacy Policy and Terms.');return}setBusy(true);const db=createClient(),callback=`${window.location.origin}/auth/callback?next=${encodeURIComponent(next)}`,result=await db.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:callback}});if(result.error){setError(friendlyError(result.error.message));setBusy(false);return}if(result.data.session){router.replace(`/onboarding?next=${encodeURIComponent(next)}`);router.refresh();return}setSent(true);setBusy(false)}if(sent)return <div className={styles.message}><strong>Check your email.</strong><br/>If an account can be created for that address, we sent a confirmation link. Open it on this device to finish signing up.</div>;return <form className={styles.form} onSubmit={submit}><label className={styles.field}>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className={styles.field}>Password<input type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label className={styles.field}>Confirm password<input type="password" autoComplete="new-password" minLength={8} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><label className={styles.consent}><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>I agree to the <a href="/terms" target="_blank">Terms of Service</a> and <a href="/privacy" target="_blank">Privacy Policy</a>.</span></label><button className={styles.button} disabled={busy}>{busy?'Creating account…':'Create account'}</button>{error&&<p role="alert" className={styles.error}>{error}</p>}</form>}

export function ForgotPasswordForm(){const[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');const callback=`${window.location.origin}/auth/callback?next=${encodeURIComponent('/reset-password')}`,result=await createClient().auth.resetPasswordForEmail(email.trim(),{redirectTo:callback});if(result.error&&(result.error.message.toLowerCase().includes('rate limit')||result.error.message.toLowerCase().includes('too many'))){setError(friendlyError(result.error.message));setBusy(false);return}setSent(true);setBusy(false)}if(sent)return <p className={styles.message}>If an account exists for that email, we sent a password-reset link. Check your inbox and spam folder.</p>;return <form className={styles.form} onSubmit={submit}><label className={styles.field}>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><button className={styles.button} disabled={busy}>{busy?'Sending…':'Send reset link'}</button>{error&&<p role="alert" className={styles.error}>{error}</p>}</form>}

export function ResetPasswordForm(){const router=useRouter(),[ready,setReady]=useState(false),[valid,setValid]=useState(false),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{let active=true;createClient().auth.getUser().then(({data})=>{if(active){setValid(Boolean(data.user));setReady(true)}});return()=>{active=false}},[]);async function submit(event:FormEvent){event.preventDefault();setError('');if(password.length<8||!/[A-Za-z]/.test(password)||!/[0-9]/.test(password)){setError('Use at least 8 characters with a letter and a number.');return}if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);const result=await createClient().auth.updateUser({password});if(result.error){setError(friendlyError(result.error.message));setBusy(false);return}router.replace('/onboarding?next=%2F');router.refresh()}if(!ready)return <p className={styles.intro}>Checking your reset link…</p>;if(!valid)return <p className={styles.error}>This reset link is invalid or expired. Request a new link from the forgot-password page.</p>;return <form className={styles.form} onSubmit={submit}><label className={styles.field}>New password<input type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label className={styles.field}>Confirm new password<input type="password" autoComplete="new-password" minLength={8} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className={styles.button} disabled={busy}>{busy?'Saving…':'Save new password'}</button>{error&&<p role="alert" className={styles.error}>{error}</p>}</form>}
