'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {paymentError} from './PlatformImage'
import s from './player-profile.module.css'
type ProfileData={profile:{id:string;display_name:string;avatar_url:string|null;city:string|null;skill_level:string|null;created_at:string;onboarding_completed_at:string|null};plus_until:string|null;counts:{hosted:number;joined:number;rounds:number};performance:{games:number;wins:number;losses:number;draws:number;points_for:number;points_against:number;average_points:number|null};matches:{round_id:string;event_id:string;title:string;number:number;court:number;pf:number;pa:number;completed_at:string;partner:string|null;opponents:string|null}[];activity:{id:string;title:string;starts_at:string;status:string;hosting:boolean;registration_status:string|null;payment_status:string|null;venue:string|null}[];activity_count:number}
const day=(v:string)=>new Date(v).toLocaleDateString('en-PH',{timeZone:'Asia/Manila',year:'numeric',month:'short',day:'numeric'})
export default function PlayerProfile({email,admin,avatar,signOut}:{email:string;admin:boolean;avatar?:string;signOut:()=>void}){
 const [data,setData]=useState<ProfileData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[view,setView]=useState('performance'),[page,setPage]=useState(0),[version,setVersion]=useState(0),[copied,setCopied]=useState(false),[imageError,setImageError]=useState(false)
 useEffect(()=>{let live=true;void(async()=>{setLoading(true);try{const r=await createClient().rpc('openly_my_profile',{p_page:page});if(r.error)throw r.error;if(!r.data?.profile)throw Error('Your player profile is unavailable.');if(live){setData(r.data);setError('')}}catch(e){if(live)setError(paymentError(e))}finally{if(live)setLoading(false)}})();return()=>{live=false}},[page,version])
 const p=data?.profile,perf=data?.performance,photo=p?.avatar_url||avatar,validPhoto=photo&&/^https:\/\//i.test(photo),initials=(p?.display_name??'Player').split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase()
 return <section className={s.profile} aria-label="Your player profile">
 {error&&<p className={s.error} role="alert">{error}</p>}
 {!data?<><p>{loading?'Loading your player profile…':'Could not load your profile.'}</p><button onClick={()=>setVersion(v=>v+1)}>Retry profile</button></>:<>
 <header className={s.hero}><div className={s.identity}><div className={s.avatar}>{validPhoto&&!imageError?<>
 {/* Google/profile photos load directly, without the shared image optimizer. */}
 {/* eslint-disable-next-line @next/next/no-img-element */}
 <img src={photo} alt={`${p!.display_name}'s profile`} referrerPolicy="no-referrer" onError={()=>setImageError(true)}/></>:<span>{initials}</span>}</div><div><span className={s.eyebrow}>YOUR PLAYER PROFILE</span><h2>{p!.display_name} {data.plus_until&&<span className={s.plusBadge}>PLUS+ ✓</span>}</h2><p>{p!.city||'Add your city'} · <span className={s.skill}>{p!.skill_level||'Skill level not set'}</span></p><small>Member since {day(p!.created_at)}</small></div></div><div className={s.membership}><span>{data.plus_until?'OPENLY PLUS':'OPENLY PLAYER'}</span><p>{data.plus_until?`Active until ${day(data.plus_until)}`:'Ready for your next game'}</p></div>
 <div className={s.heroActions}><Link className={s.primary} href="/onboarding?edit=1&next=%2F%3Ftab%3Dprofile">{p!.onboarding_completed_at?'Edit profile':'Complete profile'}</Link><button onClick={async()=>{try{await navigator.clipboard.writeText(p!.id);setCopied(true)}catch{setError('Could not copy your player ID.')}}}>{copied?'Player ID copied':'Copy player ID'}</button><button disabled={loading} onClick={()=>setVersion(v=>v+1)}>Refresh profile</button></div></header>
 <div className={s.stats}>{[['Open Plays joined',data.counts.joined],['Open Plays hosted',data.counts.hosted],['Rounds played',data.counts.rounds],['Competitive wins',perf!.wins]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
 <div className={s.tabs} role="tablist" aria-label="Player profile sections">{['performance','activity'].map(t=><button key={t} id={`profile-tab-${t}`} role="tab" aria-selected={view===t} aria-controls={`profile-panel-${t}`} onClick={()=>setView(t)} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const next=t==='performance'?'activity':'performance';setView(next);document.getElementById(`profile-tab-${next}`)?.focus()}}} tabIndex={view===t?0:-1}>{t==='performance'?'Performance':'Activity'}</button>)}</div>
 {view==='performance'?<div className={s.columns} id="profile-panel-performance" role="tabpanel" aria-labelledby="profile-tab-performance"><aside className={s.panel}><h3>Performance</h3><div className={s.rating}><span>Official DUPR rating</span><strong>Not linked</strong><small>Openly does not currently connect to DUPR.</small></div><dl>{[['Scored rounds',perf!.games],['Wins',perf!.wins],['Losses',perf!.losses],['Draws',perf!.draws],['Win rate',perf!.games?`${Math.round(perf!.wins/perf!.games*100)}%`:'—'],['Average points',perf!.average_points??'—'],['Points for / against',`${perf!.points_for} / ${perf!.points_against}`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className={s.muted}>Completed, scored Competitive regular rounds only. Each doubles partner receives the team score. Test games and championship rounds are excluded.</p></aside><section className={s.panel}><h3>Recent matches</h3>{!data.matches.length?<div className={s.empty}><span>LET’S GET YOU ON COURT</span><h4>Your match story starts here.</h4><p>Complete a scored Competitive round to see your results here.</p><Link className={s.primary} href="/?tab=discover">Explore Open Plays</Link></div>:<><p className={s.muted}>Latest 10 scored Competitive rounds</p>{data.matches.map(m=><article className={s.match} key={m.round_id}><div><span className={s.result}>{m.pf>m.pa?'WIN':m.pf<m.pa?'LOSS':'DRAW'}</span><strong className={s.score}>{m.pf} – {m.pa}</strong></div><h4>{m.title}</h4><p>Round {m.number} · Court {m.court} · {day(m.completed_at)}</p><p>Partner: {m.partner||'—'}<br/>Opponents: {m.opponents||'—'}</p><Link href={`/?join=${m.event_id}`}>View Open Play →</Link></article>)}</>}</section></div>:<section className={s.panel} id="profile-panel-activity" role="tabpanel" aria-labelledby="profile-tab-activity"><h3>Your Open Play activity</h3><p className={s.muted}>Newest scheduled games first · Test games excluded</p>{loading?<p>Loading activity…</p>:data.activity.length?data.activity.map(g=><article className={s.activity} key={g.id}><div><span className={s.eyebrow}>{g.hosting?'HOSTING':'PLAYING'}</span><h4>{g.title}</h4><p>{day(g.starts_at)} · {g.venue||'Venue unavailable'}</p></div><div><span className={s.status}>{g.status==='cancelled'?'Cancelled':g.status==='completed'?'Completed':g.hosting?g.status:g.registration_status==='confirmed'?'Confirmed':g.registration_status==='cancelled'?'Cancelled':'Pending approval'}</span><Link href={g.status==='draft'?`/host?draft=${g.id}`:`/?join=${g.id}`}>View game →</Link></div></article>):<p className={s.empty}>Join or host your first Open Play to get started.</p>}<div className={s.heroActions}><button disabled={loading||page===0} onClick={()=>setPage(v=>v-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(data.activity_count/10))}</span><button disabled={loading||(page+1)*10>=data.activity_count} onClick={()=>setPage(v=>v+1)}>Next</button></div></section>}
 </>}
 <section className={s.account}><div><h3>Account</h3><p>{email}</p><small>Your email is visible here only to you.</small></div><div className={s.heroActions}><Link href="/support">Customer support</Link><Link href="/plus">Plus & purchases</Link><button onClick={signOut}>Sign out</button></div></section>
 {admin&&<nav className={s.admin} aria-label="Administration">{[['/admin/games','Open Plays'],['/admin/venues','Venues'],['/admin/support','Support inbox'],['/admin/settings','Payment settings'],['/admin/payments','Premium payments'],['/admin/transactions','Transactions']].map(([url,label])=><Link key={url} href={url}>{label}</Link>)}</nav>}
 </section>
}
