'use client'
import {useRef} from 'react'
import s from './rotation.module.css'
const help={
 manual:{title:'Manual Play',intro:'You decide who plays, who partners up, and when players rotate.',steps:['Use the participant list to organize games yourself. Openly still handles joining, payment proof and host approval.','Arrange courts and teams outside Smart Rotation. Automatic assignments, timers and rankings are not included.','Free hosts can publish up to 3 Open Plays per Philippine day. Players never need Plus.']},
 social:{title:'Social',intro:'Relaxed doubles with balanced court time and a variety of partners.',steps:['Choose courts and timed or score-based rounds. Four confirmed players fill each court; extra players rest.','Generate a round. Players with fewer games get priority, with recent rest used to break ties. The generator tries to reduce repeat partners and opponents.','Review, regenerate or swap players before starting. Start during the scheduled game time, then complete the round manually. Scores are optional.','Generate the next round to rotate again. Requires a ₱39 unlock for this game or active host Plus; participants need neither.']},
 competitive:{title:'Competitive',intro:'Rotating doubles with individual scores and a leaderboard.',steps:['Configure courts, round type, target score and win-by rule. Generate assignments from confirmed players and review them before starting.','Record both teams’ scores on every court. Each partner receives the team’s win/loss and points. Complete the round to include it in the standings.','Regular-round rankings sort by wins, point difference, then points scored. Equal statistics share a rank. Rest rounds do not count as games.','Optionally finish with a Top 4 final or Top 8 semifinals and a final. Use a target of 11, 15 or 21; Top 8 needs two courts. Championship rounds stay separate from regular rankings.','Requires a ₱39 unlock for this game or active host Plus. These are Openly standings, not official DUPR ratings.']}
}
export default function PlayStyleHelp({style}:{style:keyof typeof help}){
 const ref=useRef<HTMLDialogElement>(null),content=help[style]
 return <><button type="button" className={s.styleHelp} aria-label={`How ${content.title} works`} title={`How ${content.title} works`} onClick={()=>ref.current?.showModal()}>?</button><dialog ref={ref} className={s.dialog} aria-label={`How ${content.title} works`} onCancel={e=>e.stopPropagation()} onClose={e=>e.stopPropagation()}><div className={s.heading}><span className={s.kicker}>PLAY STYLE GUIDE</span><button type="button" className={s.secondary} aria-label="Close play style guide" onClick={()=>ref.current?.close()}>Close ×</button></div><h2>{content.title}</h2><p>{content.intro}</p><ol className={s.helpSteps}>{content.steps.map(step=><li key={step}>{step}</li>)}</ol><p className={s.muted}>Reading this guide does not change your selected play style.</p></dialog></>
}
