'use client'
import {useRef} from 'react'
import s from './rotation.module.css'
const help={
 manual:{title:'Manual Play',intro:'You decide who plays, who partners up, and when players rotate.',steps:['Use the participant list to organize games yourself. Openly still handles joining, payment proof and host approval.','Arrange courts and teams outside Smart Rotation. Automatic assignments, timers and rankings are not included.','Free hosts can publish up to 3 Open Plays per Philippine day. Players never need Plus.']},
 social:{title:'Social',intro:'Relaxed doubles with balanced court time and a variety of partners.',steps:['Choose courts and timed or score-based rounds. Four confirmed players fill each court; extra players rest.','Generate a round. Players with fewer games get priority, with recent rest used to break ties. The generator tries to reduce repeat partners and opponents.','Review the teams before starting. Start during the scheduled game time, then complete the round manually. Scores are optional.','Each rented court runs independently. Players assigned to another court are excluded. Your first three published games include rotation; afterward use a session unlock or active host Plus. Participants need neither.']},
 competitive:{title:'Competitive',intro:'Rotating doubles with individual scores and a leaderboard.',steps:['Choose minutes (0 for no timer), race-to points and win-by. Fewer games and longer waiting get priority; recorded results balance the selected teams.','Record both teams’ scores on every court. Each partner receives the team’s win/loss and points. End the round to include it in the standings. When time expires, finish the rally and confirm the score. Higher score wins; a tie enters overtime and the next point wins.','Regular-round rankings sort by wins, point difference, then points scored. Equal statistics share a rank. Rest rounds do not count as games.','Optionally finish with a Top 4 final or Top 8 semifinals and a final. Choose a target score; Top 8 needs two courts. Championship rounds stay separate from regular rankings.','Included for your first three published games, or with a ₱39 session unlock or active host Plus. These are Openly standings, not official DUPR ratings.']}
}
export default function PlayStyleHelp({style}:{style:keyof typeof help}){
 const ref=useRef<HTMLDialogElement>(null),content=help[style]
 return <><button type="button" className={s.styleHelp} aria-label={`How ${content.title} works`} title={`How ${content.title} works`} onClick={()=>ref.current?.showModal()}>?</button><dialog ref={ref} className={s.dialog} aria-label={`How ${content.title} works`} onCancel={e=>e.stopPropagation()} onClose={e=>e.stopPropagation()}><div className={s.heading}><span className={s.kicker}>PLAY STYLE GUIDE</span><button type="button" className={s.secondary} aria-label="Close play style guide" onClick={()=>ref.current?.close()}>Close ×</button></div><h2>{content.title}</h2><p>{content.intro}</p><ol className={s.helpSteps}>{content.steps.map(step=><li key={step}>{step}</li>)}</ol><p className={s.muted}>Reading this guide does not change your selected play style.</p></dialog></>
}
