'use client'
import Link from 'next/link'
import PlayStyleHelp from './PlayStyleHelp'
import {useCallback,useEffect,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {paymentError} from './PlatformImage'
import {calculateLeaderboard,calculatePlayerHistory,championshipLayout,finalLayout,generateCourtRound,type Assignment,type RotationPlayer,type RotationRound,type RotationSettings} from '@/lib/open-play/rotation-engine'
import s from './rotation.module.css'
type State={host_id:string;court_count:number;manager:boolean;entitled:boolean;status:string;starts_at:string;ends_at:string;settings:RotationSettings;players:RotationPlayer[];rounds:RotationRound[]}
type Request={id:string;action:string;payload:Record<string,unknown>}
export default function RotationPanel({eventId,onEnded}:{eventId:string;onEnded?:()=>void}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uid,setUid]=useState(''),[view,setView]=useState(''),[unlock,setUnlock]=useState(false),[retry,setRetry]=useState(false),[now,setNow]=useState(0)
 const pending=useRef<Request|null>(null),lock=useRef(false),modal=useRef<HTMLDialogElement>(null)
 const load=useCallback(async()=>{const db=createClient(),r=await db.rpc('openly_rotation_state',{p_event:eventId});if(r.error)throw r.error;setState({...r.data,manager:r.data.host_id===(await db.auth.getUser()).data.user?.id})},[eventId])
 useEffect(()=>{let active=true;async function refresh(){try{const auth=await createClient().auth.getUser();if(active)setUid(auth.data.user?.id??'');if(active)await load()}catch(e){if(active)setError(paymentError(e))}}void refresh();const timer=window.setInterval(()=>{if(!lock.current&&document.visibilityState==='visible')void refresh()},10000);return()=>{active=false;window.clearInterval(timer)}},[load])
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[])
 useEffect(()=>{if(unlock)modal.current?.showModal();else modal.current?.close()},[unlock])
 async function command(action:string,payload:Record<string,unknown>,recover=false){if(lock.current||!state?.manager)return;lock.current=true;setBusy(true);setError('');try{
  if(!recover)pending.current={id:crypto.randomUUID(),action,payload}
  const req=pending.current;if(!req)return
  const r=await createClient().rpc('openly_rotation_command',{p_event:eventId,p_request:req.id,p_action:req.action,p_payload:req.payload})
  if(r.error){if(r.error.code&&/^[0-9A-Z]{5}$/.test(r.error.code)){pending.current=null;setRetry(false);await load()}else setRetry(true);throw r.error}
  pending.current=null;setRetry(false);setView('');await load()
 }catch(e){if(pending.current)setRetry(true);setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 async function finishEvent(){if(lock.current||!window.confirm('End this Open Play? This closes the session and locks rotation. Completed scores remain available in Results.'))return;lock.current=true;setBusy(true);setError('');try{const r=await createClient().rpc('openly_finish_event',{p_event:eventId});if(r.error)throw r.error;await load();onEnded?.()}catch(e){setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 const latest=state?.rounds.at(-1),round=state?.rounds.find(r=>r.id===view)??latest,active=state?.rounds.some(r=>['draft','live'].includes(r.status)),mutable=state&&['draft','published'].includes(state.status),canRun=state?.manager&&state.entitled&&mutable&&!busy&&!retry
 async function prepare(kind:'regular'|'semifinal'|'final'='regular',layout?:Assignment[],court?:number){if(!state)return;try{
  if(kind!=='regular'&&active)throw Error('Finish or discard the current round first.')
  const assignments=layout??generateCourtRound(state.players,state.rounds,court??1,crypto.getRandomValues(new Uint32Array(1))[0],state.settings.style)
  await command('prepare',{layout:assignments.map(a=>({player_id:a.player_id,court:a.court,team:a.team})),settings_version:state.settings.version,last:latest?.number??0,round:layout&&kind==='regular'&&round?.status==='draft'?round.id:null,version:round?.version,kind,court:court??round?.court_number})
 }catch(e){setError(paymentError(e))}}
 function championship(size:4|8){if(!state)return;try{if(size===8&&state.settings.courts<2)throw Error('Top 8 semifinals need at least two configured courts.');void prepare(size===4?'final':'semifinal',championshipLayout(state.players,state.rounds,size))}catch(e){setError(paymentError(e))}}
 const occupied=new Set(state?.rounds.filter(r=>['draft','live'].includes(r.status)).flatMap(r=>r.assignments.filter(a=>a.court>0).map(a=>a.player_id))??[])
 const standings=state?calculateLeaderboard(state.players,state.rounds):[],history=state?calculatePlayerHistory(state.players,state.rounds):null
 return <section className={s.shell} aria-label="Smart Rotation"><div className={s.heading}><div><span className={s.kicker}>PLAY MORE. PLAN LESS.</span><h2>Open Play <em>Rotation</em></h2></div><button className={s.secondary} disabled={busy} onClick={()=>{setError('');void load().catch(e=>setError(paymentError(e)))}}>Refresh rotation</button></div>
 {error&&<p className={s.error} role="alert">{error}</p>}{retry&&<p className={s.notice}>The response was interrupted. <button className={s.secondary} disabled={busy} onClick={()=>command('',{},true)}>Retry the same action</button></p>}
 {!state?<p>Rotation is available to the host and confirmed players.</p>:<>
 {state.manager&&<Config key={state.settings.version} settings={state.settings} frozen={state.rounds.some(r=>r.status!=='aborted')} locked={!state.entitled} busy={busy||retry||!!active||!mutable} onUnlock={()=>setUnlock(true)} onSave={payload=>command('configure',payload)}/>}
 {!state.manager&&<p className={s.notice}>Play style: {state.settings.style}. Your host’s access covers the whole crew—players do not need Plus.</p>}
 {state.manager&&state.entitled&&<p className={s.notice}>Smart Rotation is unlocked for this Open Play.</p>}
 {state.manager&&!state.entitled&&<p className={s.notice}>Manual Play stays free. Unlock this game for ₱39 or use active Openly Plus for Smart Rotation. Existing round history stays available. <button className={s.secondary} onClick={()=>setUnlock(true)}>View unlock options</button></p>}
 <div className={s.rest}><div className={s.heading}><h3>Waiting / Resting <span className={s.count}>{state.players.length-occupied.size}</span></h3><span className={s.muted}>{occupied.size} on court · {state.players.length} confirmed</span></div><div className={s.waiting}>{state.players.filter(p=>!occupied.has(p.id)).map(p=><PlayerChip key={p.id} name={p.display_name} own={p.user_id===uid}/>)}{state.players.length===occupied.size&&<p>Everyone is assigned to a court.</p>}</div></div>
 <div className={s.courts}>{Array.from({length:state.court_count},(_,i)=>i+1).map(court=>{
 const current=state.rounds.find(r=>['draft','live'].includes(r.status)&&r.assignments.some(a=>a.court===court))
 return <article className={s.court} key={court}><div className={s.heading}><h3 className={s.courtTitle}>Court {court}</h3>{current&&<CourtTimer round={current} court={court} now={now}/>}</div>
 {current?<><p className={s.roundLabel}>Round {state.rounds.filter(r=>r.number<=current.number&&r.assignments.some(a=>a.court===court)).length} · {current.status==='draft'?'Ready to start':current.kind==='regular'?'Now playing':current.kind}</p>
 <div className={s.courtDiagram} aria-label={`Court ${court} teams`}>{[1,2].map(team=><div className={s.courtSide} key={team}><span className={s.kicker}>TEAM {team===1?'A':'B'}</span>{current.assignments.filter(a=>a.court===court&&a.team===team).map(a=><PlayerChip key={a.player_id} name={a.display_name??'Player'} own={a.user_id===uid}/>)}</div>)}</div>
 {current.status==='live'?(state.manager?<CourtScore key={`${current.id}-${current.version}-${court}`} round={current} court={court} now={now} disabled={busy||retry||!mutable} onAction={command}/>:<div className={s.scoreboard}>{current.matches.find(m=>m.court===court)?.a??'—'} <span>:</span> {current.matches.find(m=>m.court===court)?.b??'—'}</div>):state.manager&&<button className={s.primary} disabled={!canRun} onClick={()=>command('start',{round:current.id,version:current.version})}>Start round</button>}
 {state.manager&&<details className={s.courtOptions}><summary>Round options</summary><button className={s.secondary} disabled={busy||retry||!mutable} onClick={()=>{if(window.confirm('Discard this round without adding a result?'))void command('abort',{round:current.id,version:current.version})}}>Discard {current.court_number?'round':'shared round'}</button></details>}
 </>:<div className={s.emptyCourt}><div className={s.emptyLines} aria-hidden="true"/><h4>Ready for the next four</h4><p>{state.players.length-occupied.size<4?'Waiting for four available players.':'Players will be selected from the resting pool.'}</p>{state.manager&&<button className={s.primary} disabled={!canRun||state.status!=='published'||state.settings.style==='manual'||state.players.length-occupied.size<4||state.rounds.some(r=>['draft','live'].includes(r.status)&&!r.court_number)} onClick={()=>prepare('regular',undefined,court)}>Generate next round</button>}</div>}</article>
 })}</div>
 {state.manager&&<details><summary>Court settings · {state.court_count} rented</summary><form onSubmit={e=>{e.preventDefault();void command('courts',{courts:Number(new FormData(e.currentTarget).get('courts'))})}}><label>Rented courts<input name="courts" type="number" min={1} max={20} required defaultValue={state.court_count} key={state.court_count} disabled={!!active||busy||retry||!mutable}/></label><button className={s.secondary} disabled={!!active||busy||retry||!mutable}>Update court count</button></form></details>}
 {state.status==='completed'&&<p className={s.notice}>✓ Open Play completed. Your scores are available in Results.</p>}
 {state.manager&&state.status==='published'&&<div className={s.endSession}><h3>Session controls</h3><p>Finish each round to publish its scores. End Open Play only when your entire session is finished.</p><button className={s.secondary} disabled={busy||retry||!!active||!now||Date.parse(state.starts_at)>now} onClick={finishEvent}>End Open Play</button>{!!active&&<p className={s.muted}>Finish the live round or discard its draft first.</p>}</div>}
 {state.status==='draft'&&<p>Publish this draft before generating rounds.</p>}
 {state.rounds.some(r=>r.status==='completed')&&<details><summary>Completed round history</summary><label>Round<select value={round?.id??''} onChange={e=>setView(e.target.value)}>{state.rounds.map(r=><option key={r.id} value={r.id}>Round {r.number} · {r.status}</option>)}</select></label>{round&&<div className={s.courts}>{round.matches.map(m=><div className={s.court} key={m.court}><h3>Court {m.court} · {round.status}</h3>{[1,2].map(team=><div className={s.team} key={team}><div>{round.assignments.filter(a=>a.court===m.court&&a.team===team).map(a=><strong key={a.player_id}>{a.display_name}</strong>)}</div><b>{(team===1?m.a:m.b)??'—'}</b></div>)}{state.manager&&round.status==='completed'&&mutable&&<CourtScore key={`${round.id}-${round.version}-${m.court}`} round={round} court={m.court} now={now} disabled={busy||retry} onAction={command}/>}</div>)}</div>}</details>}
 <details><summary>{state.settings.style==='competitive'?'Session standings':'Games played & court time'}</summary>
 {state.settings.style==='competitive'||state.rounds.some(r=>r.settings.style==='competitive')?<><h3>Individual leaderboard</h3><p className={s.muted}>Completed regular rounds · Wins, point difference, then points for. Equal totals share a rank.</p><div className={s.tableScroll}><table><thead><tr><th>Rank</th><th>Player</th><th>GP</th><th>W</th><th>L</th><th>D</th><th>PF</th><th>PA</th><th>+/−</th></tr></thead><tbody>{standings.map(p=><tr key={p.id}><td>{p.rank}</td><td>{p.name}</td><td>{p.games}</td><td>{p.wins}</td><td>{p.losses}</td><td>{p.draws}</td><td>{p.pf}</td><td>{p.pa}</td><td>{p.pf-p.pa}</td></tr>)}</tbody></table></div></>:<><h3>Social court time</h3><div className={s.tableScroll}><table><thead><tr><th>Player</th><th>Played</th><th>Minutes*</th><th>Partners</th><th>Opponents</th></tr></thead><tbody>{[...(history?.stats.values()??[])].map(p=><tr key={p.id}><td>{p.name}</td><td>{p.games}</td><td>{Math.round(p.minutes)}</td><td>{p.partners.size}</td><td>{p.opponents.size}</td></tr>)}</tbody></table></div><p className={s.muted}>*Approximate court time from round start to completion.</p></>}
 </details>
 {state.manager&&state.settings.style==='competitive'&&<details><summary>Optional championship</summary><p>Top 4: #1 + #4 vs #2 + #3. Top 8: two semifinals, then the winning teams play the final. Championship rounds do not change regular standings. Tied seeds use a stable order.</p><p>Championship uses the configured target, win-by and score cap. No championship is required.</p><div className={s.actions}><button className={s.secondary} disabled={!canRun||!!active} onClick={()=>championship(4)}>Create Top 4 final</button><button className={s.secondary} disabled={!canRun||!!active} onClick={()=>championship(8)}>Create Top 8 semifinals</button>{latest?.kind==='semifinal'&&latest.status==='completed'&&<button className={s.primary} disabled={!canRun} onClick={()=>{try{void prepare('final',finalLayout(state.players,latest))}catch(e){setError(paymentError(e))}}}>Create championship final</button>}</div></details>}
 </>}
 {state?.manager&&<dialog ref={modal} className={s.dialog} onCancel={e=>e.stopPropagation()} onClose={e=>{e.stopPropagation();setUnlock(false)}} aria-label="Unlock Smart Rotation"><span className={s.kicker}>HOST SMARTER</span><h2>Unlock Smart Rotation</h2><p>Social: fair court time and rotating partners.<br/>Competitive: individual scores, rankings and an optional championship.</p><div className={s.actions}><Link className={s.primary} target="_blank" href={`/plus?game=${eventId}`} onClick={()=>setUnlock(false)}>Unlock this game · ₱39 ↗</Link><Link className={s.secondary} target="_blank" href="/plus" onClick={()=>setUnlock(false)}>Openly Plus · ₱399/month ↗</Link><button className={s.secondary} onClick={()=>setUnlock(false)}>Continue with Free</button></div><p>After admin approval, refresh rotation. The ₱39 unlock does not remove Free’s daily hosting limit.</p></dialog>}
 </section>
}
function Config({settings,frozen,locked,busy,onUnlock,onSave}:{settings:RotationSettings;frozen:boolean;locked:boolean;busy:boolean;onUnlock:()=>void;onSave:(p:Record<string,unknown>)=>Promise<void>}){
 const [style,setStyle]=useState(settings.style)
 if(frozen)return <div className={s.config}><div className={s.heading}><h3>{settings.style==='social'?'Social':'Competitive'} play</h3><span className={s.badge}>{settings.courts} courts</span></div><p>{settings.minutes>0&&settings.round_type==='timed'?`${settings.minutes} min / round`:'No time limit'} · Race to {settings.target} · Win by {settings.win_by}</p></div>
 return <form className={s.config} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void onSave({version:settings.version,style,minutes:Number(f.get('minutes')),target:Number(f.get('target')),win_by:Number(f.get('win_by')),score_cap:null})}}><div className={s.heading}><h3>Play style</h3><span className={s.badge}>{settings.courts} rented courts</span></div><div className={s.styles}>{(['manual','social','competitive'] as const).map(v=><div key={v} className={s.styleOption}><button className={s.styleSelect} type="button" aria-pressed={style===v} disabled={busy} onClick={()=>{if(v!=='manual'&&locked)onUnlock();else setStyle(v)}}><strong>{v==='manual'?'Manual Play':v==='social'?'Social':'Competitive'}</strong><small>{v==='manual'?'Organize games yourself':v==='social'?'Mix partners · Fair court time':'Balanced teams · Scores & standings'}</small></button><PlayStyleHelp style={v}/></div>)}</div><fieldset disabled={busy}><div className={s.row}><label>Minutes / Round<input name="minutes" type="number" min={0} max={180} required defaultValue={settings.round_type==='score'?0:settings.minutes}/><small>0 = no time limit</small></label><label>Race to Points<input name="target" type="number" min={1} max={199} required defaultValue={settings.target??11}/></label><label>Win by<select name="win_by" defaultValue={settings.win_by}><option value={1}>1 point</option><option value={2}>2 points</option></select></label></div><button className={s.primary}>Save settings</button></fieldset><p className={s.muted}>Save your settings, then generate a round on each court. Settings lock when the first round is generated.</p></form>
}
function PlayerChip({name,own=false}:{name:string;own?:boolean}){return <div className={s.player}><span className={s.avatar} aria-hidden="true">{name.trim().split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase()}</span><span>{name}{own&&<small> You</small>}</span></div>}
function CourtTimer({round,court,now}:{round:RotationRound;court:number;now:number}){
 const match=round.matches.find(m=>m.court===court),timed=round.settings.round_type==='timed'&&round.settings.minutes>0
 const left=timed?Math.max(0,round.settings.minutes*60-(now&&round.started_at?Math.max(0,Math.floor((now-Date.parse(round.started_at))/1000)):0)):0
 const overtime=match?.timeout_a!=null&&match.timeout_a===match.timeout_b
 return <span className={s.clock} role="timer">{round.status==='draft'?'Ready':!timed?'Untimed':overtime?'Over time':left>0?`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`:match?.a!=null&&match.a===match.b?'Over time':'Time’s up'}</span>
}
function CourtScore({round,court,now,disabled,onAction}:{round:RotationRound;court:number;now:number;disabled:boolean;onAction:(action:string,p:Record<string,unknown>)=>Promise<void>}){
 const match=round.matches.find(m=>m.court===court),[a,setA]=useState(match?.a?.toString()??''),[b,setB]=useState(match?.b?.toString()??'')
 const expired=round.status==='live'&&round.kind==='regular'&&round.settings.round_type==='timed'&&round.settings.minutes>0&&now>=Date.parse(round.started_at??'')+round.settings.minutes*60000
 const overtime=match?.timeout_a!=null&&match.timeout_a===match.timeout_b,competitive=round.settings.style==='competitive'||round.kind!=='regular'
 const targetReached=a!==''&&b!==''&&Number(a)!==Number(b)&&Math.max(Number(a),Number(b))>=round.settings.target&&(Math.abs(Number(a)-Number(b))>=round.settings.win_by||Math.max(Number(a),Number(b))===round.settings.score_cap)
 const needsTimeout=expired&&competitive&&match?.timeout_a==null&&!targetReached
 return <form onSubmit={e=>{e.preventDefault();const action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')??'score';void onAction(action,{round:round.id,version:round.version,scores:[{court,a:a===''?null:Number(a),b:b===''?null:Number(b)}]})}}><fieldset disabled={disabled}><div className={s.scoreInputs}><label>Team A<input aria-label={`Court ${court} Team A score`} type="number" min={0} max={199} required={competitive||b!==''} value={a} onChange={e=>setA(e.target.value)}/></label><span>:</span><label>Team B<input aria-label={`Court ${court} Team B score`} type="number" min={0} max={199} required={competitive||a!==''} value={b} onChange={e=>setB(e.target.value)}/></label></div>
 {expired&&round.status==='live'&&<p className={s.muted}>{overtime?'Over time · Next point wins.':needsTimeout?'Finish the current rally, enter the score, then confirm. A tie enters overtime.':'Finish the current rally before ending the round.'}</p>}
 <div className={s.actions}><button className={s.secondary} value="score">Save score</button>{round.status==='live'&&(needsTimeout?<button className={s.primary} value="timeout">Confirm timeout score</button>:<button className={s.primary} value="complete">{round.court_number?'End round':'End shared round'}</button>)}</div></fieldset>{!competitive&&<p className={s.muted}>Scores are optional in Social.</p>}
 </form>
}
