'use client'
import Link from 'next/link'
import PlayStyleHelp from './PlayStyleHelp'
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react'
import {createClient} from '@/lib/supabase/client'
import {paymentError} from './PlatformImage'
import {calculateLeaderboard,calculatePlayerHistory,championshipLayout,finalLayout,generateCourtRound,type Assignment,type RotationPlayer,type RotationRound,type RotationSettings} from '@/lib/open-play/rotation-engine'
import s from './rotation.module.css'
type State={host_id:string;court_count:number;manager:boolean;entitled:boolean;status:string;starts_at:string;ends_at:string;settings:RotationSettings;players:RotationPlayer[];rounds:RotationRound[]}
type Request={id:string;action:string;payload:Record<string,unknown>}
export default function RotationPanel({eventId,onEnded}:{eventId:string;onEnded?:()=>void}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uid,setUid]=useState(''),[view,setView]=useState(''),[unlock,setUnlock]=useState(false),[retry,setRetry]=useState(false),[now,setNow]=useState(0)
 const pending=useRef<Request|null>(null),lock=useRef(false),modal=useRef<HTMLDialogElement>(null)
 const load=useCallback(async()=>{const db=createClient(),r=await db.rpc('openly_rotation_state',{p_event:eventId});if(r.error)throw r.error;setState({...r.data,manager:r.data.host_id===(await db.auth.getUser()).data.user?.id})},[eventId])
 useEffect(()=>{let active=true;async function refresh(){try{const auth=await createClient().auth.getUser();if(active)setUid(auth.data.user?.id??'');if(active)await load()}catch(e){if(active)setError(paymentError(e))}}void refresh();const timer=window.setInterval(()=>{if(!lock.current&&document.visibilityState==='visible')void refresh()},10000);return()=>{active=false;window.clearInterval(timer)}},[load])
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[])
 useEffect(()=>{if(unlock)modal.current?.showModal();else modal.current?.close()},[unlock])
 async function command(action:string,payload:Record<string,unknown>,recover=false){if(lock.current||!state?.manager)return;lock.current=true;setBusy(true);setError('');try{
  if(!recover)pending.current={id:crypto.randomUUID(),action,payload}
  const req=pending.current;if(!req)return
  const r=await createClient().rpc('openly_rotation_command',{p_event:eventId,p_request:req.id,p_action:req.action,p_payload:req.payload})
  if(r.error){if(r.error.code&&/^[0-9A-Z]{5}$/.test(r.error.code)){pending.current=null;setRetry(false);await load()}else setRetry(true);throw r.error}
  pending.current=null;setRetry(false);setView('');await load()
 }catch(e){if(pending.current)setRetry(true);setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 async function finishEvent(){if(lock.current||!window.confirm('End this Open Play? This closes the session and locks rotation. Completed scores remain available in Results.'))return;lock.current=true;setBusy(true);setError('');try{const r=await createClient().rpc('openly_finish_event',{p_event:eventId});if(r.error)throw r.error;await load();onEnded?.()}catch(e){setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 const latest=state?.rounds.at(-1),round=state?.rounds.find(r=>r.id===view)??latest,active=state?.rounds.some(r=>['draft','live'].includes(r.status)),mutable=state&&['draft','published'].includes(state.status),canRun=state?.manager&&state.entitled&&mutable&&!busy&&!retry
 async function prepare(kind:'regular'|'semifinal'|'final'='regular',layout?:Assignment[],court?:number){if(!state)return;try{
  if(kind!=='regular'&&active)throw Error('Finish or discard the current round first.')
  const assignments=layout??generateCourtRound(state.players,state.rounds,court??1,crypto.getRandomValues(new Uint32Array(1))[0],state.settings.style)
  await command('prepare',{layout:assignments.map(a=>({player_id:a.player_id,court:a.court,team:a.team})),settings_version:state.settings.version,last:latest?.number??0,round:layout&&kind==='regular'&&round?.status==='draft'?round.id:null,version:round?.version,kind,court:court??round?.court_number})
 }catch(e){setError(paymentError(e))}}
 function championship(size:4|8){if(!state)return;try{if(size===8&&state.settings.courts<2)throw Error('Top 8 semifinals need at least two configured courts.');void prepare(size===4?'final':'semifinal',championshipLayout(state.players,state.rounds,size))}catch(e){setError(paymentError(e))}}
 const occupied=new Set(state?.rounds.filter(r=>['draft','live'].includes(r.status)).flatMap(r=>r.assignments.filter(a=>a.court>0).map(a=>a.player_id))??[])
 const standings=state?calculateLeaderboard(state.players,state.rounds):[],history=state?calculatePlayerHistory(state.players,state.rounds):null
 return <section className={`${s.shell} ${s.dashboard}`} aria-label="Smart Rotation"><header className={s.topbar}><div className={s.brand}><span className={s.brandIcon} aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="9"/>{[[8,8],[15,7],[7,14],[15,15],[12,11]].map(([cx,cy],i)=><circle key={i} cx={cx} cy={cy} r="1.3" fill="currentColor" stroke="none"/>)}</svg></span><div><h2>Open Play Rotation</h2><span className={s.kicker}>SMART ROTATION</span></div></div><div className={s.headerStats}>{[['Players',state?.players.length??0,'Total'],['On court',occupied.size,'Assigned'],['Queue',(state?.players.length??0)-occupied.size,'Resting']].map(([label,count,detail])=><div className={s.stat} key={label}><span>{label}</span><strong>{count} <small>{detail}</small></strong></div>)}<button className={s.refresh} aria-label="Refresh rotation" title="Refresh rotation" disabled={busy} onClick={()=>{setError('');void load().catch(e=>setError(paymentError(e)))}}>↻</button></div></header>
 {error&&<p className={s.error} role="alert">{error}</p>}{retry&&<p className={s.notice}>The response was interrupted. <button className={s.secondary} disabled={busy} onClick={()=>command('',{},true)}>Retry the same action</button></p>}
 {!state?<p>Rotation is available to the host and confirmed players.</p>:<>
 {state.manager&&<Config key={state.settings.version} settings={state.settings} frozen={state.rounds.some(r=>r.status!=='aborted')} locked={!state.entitled} busy={busy||retry||!!active||!mutable} onUnlock={()=>setUnlock(true)} onSave={payload=>command('configure',payload)}/>}
 {!state.manager&&<p className={s.notice}>Play style: {state.settings.style}. Your host’s access covers the whole crew—players do not need Plus.</p>}

 {state.manager&&!state.entitled&&<p className={s.notice}>Manual Play stays free. Unlock this game for ₱39 or use active Openly Plus for Smart Rotation. Existing round history stays available. <button className={s.secondary} onClick={()=>setUnlock(true)}>View unlock options</button></p>}
 <section className={s.rest}><div className={s.benchHeading}><h3><span className={s.dot}/>Waiting / Resting <span>({state.players.length-occupied.size})</span></h3><p>Fewer games and longer rest get priority.</p></div><div className={s.waiting}>{state.players.filter(p=>!occupied.has(p.id)).map(p=><PlayerChip key={p.id} name={p.display_name} own={p.user_id===uid} games={history?.stats.get(p.id)?.games??0}/>)}{state.players.length===occupied.size&&<p className={s.emptyBench}>Everyone is assigned to a court.</p>}</div></section>
 <div className={s.gridHeading}><h3><span className={s.dot}/>Active courts</h3><span>Live scores · Independent rounds</span></div>
 <div className={s.courts}>{Array.from({length:state.court_count},(_,i)=>i+1).map(court=>{
 const current=state.rounds.find(r=>['draft','live'].includes(r.status)&&r.assignments.some(a=>a.court===court))
 const diagram=<CourtDiagram assignments={current?.assignments??[]} court={court} uid={uid}/>
 return <article className={`${s.court} ${current?.status==='live'?s.liveCourt:''}`} key={court}><div className={s.courtHeader}><div><h3>Court {court}</h3><span className={s.courtStatus} data-live={current?.status==='live'}>{current?.status==='live'?'In game':current?'Ready':'Idle'}</span></div>{current?<CourtTimer round={current} court={court} now={now}/>:<span className={s.clock}><ClockIcon/>— : —</span>}</div>
 {current?<>{current.status==='live'?(state.manager?<CourtScore key={`${current.id}-${current.version}-${court}`} round={current} court={court} now={now} disabled={busy||retry||!mutable} onAction={command}>{diagram}</CourtScore>:<><div className={s.readScore}><span>Team A <b>{current.matches.find(m=>m.court===court)?.a??'—'}</b></span><small>VS</small><span>Team B <b>{current.matches.find(m=>m.court===court)?.b??'—'}</b></span></div>{diagram}</>):<>{state.manager&&<button className={`${s.primary} ${s.fullButton}`} disabled={!canRun} onClick={()=>command('start',{round:current.id,version:current.version})}>▷ Start round</button>}{diagram}</>}
 <div className={s.roundFooter}><span>Round {state.rounds.filter(r=>r.number<=current.number&&r.assignments.some(a=>a.court===court)).length}{current.kind!=='regular'?` · ${current.kind}`:''}</span>{state.manager&&<details className={s.courtOptions}><summary>Options</summary><button className={s.secondary} disabled={busy||retry||!mutable} onClick={()=>{if(window.confirm('Discard this round without adding a result?'))void command('abort',{round:current.id,version:current.version})}}>Discard {current.court_number?'round':'shared round'}</button></details>}</div>
 </>:<>{state.manager&&<button className={`${s.primary} ${s.fullButton}`} disabled={!canRun||state.status!=='published'||state.settings.style==='manual'||state.players.length-occupied.size<4||state.rounds.some(r=>['draft','live'].includes(r.status)&&!r.court_number)} onClick={()=>prepare('regular',undefined,court)}>▷ Generate next round</button>}{diagram}<p className={s.idleHint}>{state.players.length-occupied.size<4?'Waiting for four available players.':'Four resting players will be assigned here.'}</p></>}</article>
 })}</div>
 {state.manager&&<details><summary>Court settings · {state.court_count} rented</summary><form onSubmit={e=>{e.preventDefault();void command('courts',{courts:Number(new FormData(e.currentTarget).get('courts'))})}}><label>Rented courts<input name="courts" type="number" min={1} max={20} required defaultValue={state.court_count} key={state.court_count} disabled={!!active||busy||retry||!mutable}/></label><button className={s.secondary} disabled={!!active||busy||retry||!mutable}>Update court count</button></form></details>}
 {state.status==='completed'&&<p className={s.notice}>✓ Open Play completed. Your scores are available in Results.</p>}
 {state.manager&&state.status==='published'&&<details className={s.endSession}><summary>End this Open Play</summary><p>Finish each round to publish its scores. End Open Play only when your entire session is finished.</p><button className={s.secondary} disabled={busy||retry||!!active||!now||Date.parse(state.starts_at)>now} onClick={finishEvent}>End Open Play</button>{!!active&&<p className={s.muted}>Finish the live round or discard its draft first.</p>}</details>}
 {state.status==='draft'&&<p>Publish this draft before generating rounds.</p>}
 {state.rounds.some(r=>r.status==='completed')&&<details><summary>Completed round history</summary><label>Round<select value={round?.id??''} onChange={e=>setView(e.target.value)}>{state.rounds.map(r=><option key={r.id} value={r.id}>Round {r.number} · {r.status}</option>)}</select></label>{round&&<div className={s.courts}>{round.matches.map(m=><div className={s.court} key={m.court}><h3>Court {m.court} · {round.status}</h3>{[1,2].map(team=><div className={s.team} key={team}><div>{round.assignments.filter(a=>a.court===m.court&&a.team===team).map(a=><strong key={a.player_id}>{a.display_name}</strong>)}</div><b>{(team===1?m.a:m.b)??'—'}</b></div>)}{state.manager&&round.status==='completed'&&mutable&&<CourtScore key={`${round.id}-${round.version}-${m.court}`} round={round} court={m.court} now={now} disabled={busy||retry} onAction={command}/>}</div>)}</div>}</details>}
 <details><summary>{state.settings.style==='competitive'?'Session standings':'Games played & court time'}</summary>
 {state.settings.style==='competitive'||state.rounds.some(r=>r.settings.style==='competitive')?<><h3>Individual leaderboard</h3><p className={s.muted}>Completed regular rounds · Wins, point difference, then points for. Equal totals share a rank.</p><div className={s.tableScroll}><table><thead><tr><th>Rank</th><th>Player</th><th>GP</th><th>W</th><th>L</th><th>D</th><th>PF</th><th>PA</th><th>+/−</th></tr></thead><tbody>{standings.map(p=><tr key={p.id}><td>{p.rank}</td><td>{p.name}</td><td>{p.games}</td><td>{p.wins}</td><td>{p.losses}</td><td>{p.draws}</td><td>{p.pf}</td><td>{p.pa}</td><td>{p.pf-p.pa}</td></tr>)}</tbody></table></div></>:<><h3>Social court time</h3><div className={s.tableScroll}><table><thead><tr><th>Player</th><th>Played</th><th>Minutes*</th><th>Partners</th><th>Opponents</th></tr></thead><tbody>{[...(history?.stats.values()??[])].map(p=><tr key={p.id}><td>{p.name}</td><td>{p.games}</td><td>{Math.round(p.minutes)}</td><td>{p.partners.size}</td><td>{p.opponents.size}</td></tr>)}</tbody></table></div><p className={s.muted}>*Approximate court time from round start to completion.</p></>}
 </details>
 {state.manager&&state.settings.style==='competitive'&&<details><summary>Optional championship</summary><p>Top 4: #1 + #4 vs #2 + #3. Top 8: two semifinals, then the winning teams play the final. Championship rounds do not change regular standings. Tied seeds use a stable order.</p><p>Championship uses the configured target, win-by and score cap. No championship is required.</p><div className={s.actions}><button className={s.secondary} disabled={!canRun||!!active} onClick={()=>championship(4)}>Create Top 4 final</button><button className={s.secondary} disabled={!canRun||!!active} onClick={()=>championship(8)}>Create Top 8 semifinals</button>{latest?.kind==='semifinal'&&latest.status==='completed'&&<button className={s.primary} disabled={!canRun} onClick={()=>{try{void prepare('final',finalLayout(state.players,latest))}catch(e){setError(paymentError(e))}}}>Create championship final</button>}</div></details>}
 </>}
 {state?.manager&&<dialog ref={modal} className={s.dialog} onCancel={e=>e.stopPropagation()} onClose={e=>{e.stopPropagation();setUnlock(false)}} aria-label="Unlock Smart Rotation"><span className={s.kicker}>HOST SMARTER</span><h2>Unlock Smart Rotation</h2><p>Social: fair court time and rotating partners.<br/>Competitive: individual scores, rankings and an optional championship.</p><div className={s.actions}><Link className={s.primary} target="_blank" href={`/plus?game=${eventId}`} onClick={()=>setUnlock(false)}>Unlock this game · ₱39 ↗</Link><Link className={s.secondary} target="_blank" href="/plus" onClick={()=>setUnlock(false)}>Openly Plus · ₱399/month ↗</Link><button className={s.secondary} onClick={()=>setUnlock(false)}>Continue with Free</button></div><p>After admin approval, refresh rotation. The ₱39 unlock does not remove Free’s daily hosting limit.</p></dialog>}
 </section>
}
function Config({settings,frozen,locked,busy,onUnlock,onSave}:{settings:RotationSettings;frozen:boolean;locked:boolean;busy:boolean;onUnlock:()=>void;onSave:(p:Record<string,unknown>)=>Promise<void>}){
 const [style,setStyle]=useState(settings.style)
 return <form className={s.config} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void onSave({version:settings.version,style,minutes:Number(f.get('minutes')),target:Number(f.get('target')),win_by:Number(f.get('win_by')),score_cap:null})}}><div className={s.configTitle}><h3>Session controls</h3><span>{frozen?'Settings locked':'Configure your session'}</span></div><fieldset disabled={busy||frozen} className={s.settingsGrid}><div><div className={s.styleLabel}><label htmlFor="rotation-playstyle">Play style</label><PlayStyleHelp style={style}/></div><select id="rotation-playstyle" value={style} onChange={e=>{const next=e.target.value as RotationSettings['style'];if(next!=='manual'&&locked)onUnlock();else setStyle(next)}}><option value="manual">Manual Play</option><option value="social">Social</option><option value="competitive">Competitive</option></select></div><label>Rented courts<output className={s.courtCount}>{settings.courts}<small>courts</small></output></label><label>Minutes / Round<input name="minutes" type="number" min={0} max={180} required defaultValue={settings.round_type==='score'?0:settings.minutes}/><small>0 = no time limit</small></label><label>Race to Points<input name="target" type="number" min={1} max={199} required defaultValue={settings.target??11}/></label><label>Win by<select name="win_by" defaultValue={settings.win_by}><option value={1}>1 point</option><option value={2}>2 points</option></select></label><button className={s.primary}>{frozen?'✓ Saved':'✓ Save settings'}</button></fieldset></form>
}
function PlayerChip({name,own=false,games}:{name:string;own?:boolean;games?:number}){return <div className={games==null?s.player:s.waitingPlayer} title={name}><span className={s.avatar} aria-hidden="true">{name.trim().split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase()}</span><span className={s.playerInfo}><strong>{name}{own&&<small> · You</small>}</strong>{games!=null&&<small>{games} {games===1?'game':'games'} played</small>}</span></div>}
function ClockIcon(){return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>}
function CourtDiagram({assignments,court,uid}:{assignments:Assignment[];court:number;uid:string}){return <div className={s.courtDiagram} aria-label={`Court ${court} teams`}>{[1,2].map(team=>{const players=assignments.filter(a=>a.court===court&&a.team===team);return <div className={s.courtSide} data-team={team} key={team}><span className={s.kitchen} aria-hidden="true">Kitchen</span><span className={s.serviceLine} aria-hidden="true"/><span className={s.teamLabel}>TEAM {team===1?'A':'B'}</span>{[0,1].map(i=>players[i]?<PlayerChip key={players[i].player_id} name={players[i].display_name??'Player'} own={players[i].user_id===uid}/>:<span className={s.emptySlot} key={i}>Empty slot</span>)}</div>})}<span className={s.net} aria-hidden="true"><span>NET</span></span></div>}
function CourtTimer({round,court,now}:{round:RotationRound;court:number;now:number}){
 const match=round.matches.find(m=>m.court===court),timed=round.settings.round_type==='timed'&&round.settings.minutes>0
 const left=timed?Math.max(0,round.settings.minutes*60-(now&&round.started_at?Math.max(0,Math.floor((now-Date.parse(round.started_at))/1000)):0)):0
 const overtime=match?.timeout_a!=null&&match.timeout_a===match.timeout_b
 return <span className={s.clock} role="timer"><ClockIcon/>{round.status==='draft'?'Ready':!timed?'Untimed':overtime?'Over time':left>0?`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`:match?.a!=null&&match.a===match.b?'Over time':'Time’s up'}</span>
}
function CourtScore({round,court,now,disabled,onAction,children}:{round:RotationRound;court:number;now:number;disabled:boolean;children?:ReactNode;onAction:(action:string,p:Record<string,unknown>)=>Promise<void>}){
 const match=round.matches.find(m=>m.court===court),[a,setA]=useState(match?.a?.toString()??''),[b,setB]=useState(match?.b?.toString()??'')
 const expired=round.status==='live'&&round.kind==='regular'&&round.settings.round_type==='timed'&&round.settings.minutes>0&&now>=Date.parse(round.started_at??'')+round.settings.minutes*60000
 const overtime=match?.timeout_a!=null&&match.timeout_a===match.timeout_b,competitive=round.settings.style==='competitive'||round.kind!=='regular'
 const targetReached=a!==''&&b!==''&&Number(a)!==Number(b)&&Math.max(Number(a),Number(b))>=round.settings.target&&(Math.abs(Number(a)-Number(b))>=round.settings.win_by||Math.max(Number(a),Number(b))===round.settings.score_cap)
 const needsTimeout=expired&&competitive&&match?.timeout_a==null&&!targetReached
 function step(team:'a'|'b',delta:number){const next=String(Math.max(0,Math.min(199,Number(team==='a'?a:b)+delta)));if(team==='a'){setA(next);if(b==='')setB('0')}else{setB(next);if(a==='')setA('0')}}
 return <form className={s.scoreForm} onSubmit={e=>{e.preventDefault();const action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')??'score';void onAction(action,{round:round.id,version:round.version,scores:[{court,a:a===''?null:Number(a),b:b===''?null:Number(b)}]})}}><fieldset disabled={disabled}><div className={s.scoreInputs}>{(['a','b'] as const).map((team,i)=><div className={s.scoreTeam} key={team} data-team={team}><span>Team {team.toUpperCase()}</span><div><button type="button" aria-label={`Court ${court} Team ${team.toUpperCase()} minus one`} onClick={()=>step(team,-1)}>−</button><input aria-label={`Court ${court} Team ${team.toUpperCase()} score`} type="number" inputMode="numeric" min={0} max={199} placeholder="0" required={competitive||(i===0?b:a)!==''} value={i===0?a:b} onChange={e=>(i===0?setA:setB)(e.target.value)}/><button type="button" aria-label={`Court ${court} Team ${team.toUpperCase()} plus one`} onClick={()=>step(team,1)}>+</button></div></div>)}<span className={s.scoreVs}>VS<small>to {round.settings.target}</small></span></div>
 {children}
 {expired&&round.status==='live'&&<p className={s.muted}>{overtime?'Over time · Next point wins.':needsTimeout?'Finish the current rally, enter the score, then confirm. A tie enters overtime.':'Finish the current rally before ending the round.'}</p>}
 <div className={s.scoreSave}><span>{!competitive?'Scores optional in Social':'Scores required'}</span><button className={s.textButton} value="score">Save score</button></div>{round.status==='live'&&(needsTimeout?<button className={`${s.primary} ${s.fullButton}`} value="timeout">Confirm timeout score</button>:<button className={s.endRound} value="complete">✓ {round.court_number?'End round':'End shared round'} <span>· Rotate players</span></button>)}</fieldset>
 </form>
}
