'use client'
import Link from 'next/link'
import PlayStyleHelp from './PlayStyleHelp'
import {useCallback,useEffect,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {paymentError} from './PlatformImage'
import {calculateLeaderboard,calculatePlayerHistory,championshipLayout,finalLayout,generateNextRound,type Assignment,type RotationPlayer,type RotationRound,type RotationSettings} from '@/lib/open-play/rotation-engine'
import s from './rotation.module.css'
type State={manager:boolean;entitled:boolean;status:string;starts_at:string;ends_at:string;settings:RotationSettings;players:RotationPlayer[];rounds:RotationRound[]}
type Request={id:string;action:string;payload:Record<string,unknown>}
export default function RotationPanel({eventId,onEnded}:{eventId:string;onEnded?:()=>void}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uid,setUid]=useState(''),[view,setView]=useState(''),[unlock,setUnlock]=useState(false),[retry,setRetry]=useState(false),[swapA,setSwapA]=useState(''),[swapB,setSwapB]=useState(''),[now,setNow]=useState(0)
 const pending=useRef<Request|null>(null),lock=useRef(false),modal=useRef<HTMLDialogElement>(null)
 const load=useCallback(async()=>{const db=createClient(),r=await db.rpc('openly_rotation_state',{p_event:eventId});if(r.error)throw r.error;setState(r.data)},[eventId])
 useEffect(()=>{let active=true;async function refresh(){try{const auth=await createClient().auth.getUser();if(active)setUid(auth.data.user?.id??'');if(active)await load()}catch(e){if(active)setError(paymentError(e))}}void refresh();const timer=window.setInterval(()=>{if(!lock.current&&document.visibilityState==='visible')void refresh()},10000);return()=>{active=false;window.clearInterval(timer)}},[load])
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[])
 useEffect(()=>{if(unlock)modal.current?.showModal();else modal.current?.close()},[unlock])
 async function command(action:string,payload:Record<string,unknown>,recover=false){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{
  if(!recover)pending.current={id:crypto.randomUUID(),action,payload}
  const req=pending.current;if(!req)return
  const r=await createClient().rpc('openly_rotation_command',{p_event:eventId,p_request:req.id,p_action:req.action,p_payload:req.payload})
  if(r.error){if(r.error.code&&/^[0-9A-Z]{5}$/.test(r.error.code)){pending.current=null;setRetry(false);await load()}else setRetry(true);throw r.error}
  pending.current=null;setRetry(false);setView('');await load()
 }catch(e){if(pending.current)setRetry(true);setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 async function finishEvent(){if(lock.current||!window.confirm('End this Open Play? This closes the session and locks rotation. Completed scores remain available in Results.'))return;lock.current=true;setBusy(true);setError('');try{const r=await createClient().rpc('openly_finish_event',{p_event:eventId});if(r.error)throw r.error;await load();onEnded?.()}catch(e){setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 const latest=state?.rounds.at(-1),round=state?.rounds.find(r=>r.id===view)??latest,active=latest&&['draft','live'].includes(latest.status),mutable=state&&['draft','published'].includes(state.status),canRun=state?.manager&&state.entitled&&mutable&&!busy&&!retry
 async function prepare(kind:'regular'|'semifinal'|'final'='regular',layout?:Assignment[]){if(!state)return;try{
  if(kind!=='regular'&&active&&latest?.status!=='draft')throw Error('Finish or discard the current round first.')
  const assignments=layout??generateNextRound(state.players,state.rounds,state.settings.courts,crypto.getRandomValues(new Uint32Array(1))[0])
  await command('prepare',{layout:assignments.map(a=>({player_id:a.player_id,court:a.court,team:a.team})),settings_version:state.settings.version,last:latest?.number??0,round:latest?.status==='draft'?latest.id:null,version:latest?.version,kind})
 }catch(e){setError(paymentError(e))}}
 function championship(size:4|8){if(!state)return;try{if(size===8&&state.settings.courts<2)throw Error('Top 8 semifinals need at least two configured courts.');void prepare(size===4?'final':'semifinal',championshipLayout(state.players,state.rounds,size))}catch(e){setError(paymentError(e))}}
 const standings=state?calculateLeaderboard(state.players,state.rounds):[],history=state?calculatePlayerHistory(state.players,state.rounds):null,own=round?.assignments.find(a=>a.user_id===uid),elapsed=round?.started_at?Math.max(0,Math.floor((now-Date.parse(round.started_at))/1000)):0,left=round?Math.max(0,round.settings.minutes*60-elapsed):0
 return <section className={s.shell} aria-label="Smart Rotation"><div className={s.heading}><div><span className={s.kicker}>PLAY MORE. PLAN LESS.</span><h2>Smart Rotation</h2></div><button className={s.secondary} disabled={busy} onClick={()=>{setError('');void load().catch(e=>setError(paymentError(e)))}}>Refresh rotation</button></div>
 {error&&<p className={s.error} role="alert">{error}</p>}{retry&&<p className={s.notice}>The response was interrupted. <button className={s.secondary} disabled={busy} onClick={()=>command('',{},true)}>Retry the same action</button></p>}
 {!state?<p>Rotation is available to the host and confirmed players.</p>:<>
 {state.manager&&<Config key={state.settings.version} settings={state.settings} locked={!state.entitled} busy={busy||retry||!!active||!mutable} onUnlock={()=>setUnlock(true)} onSave={payload=>command('configure',payload)}/>}
 {!state.manager&&<p className={s.notice}>Play style: {state.settings.style}. Your host’s access covers the whole crew—players do not need Plus.</p>}
 {state.manager&&state.entitled&&<p className={s.notice}>Smart Rotation is unlocked for this Open Play.</p>}
 {state.manager&&!state.entitled&&<p className={s.notice}>Manual Play stays free. Unlock this game for ₱39 or use active Openly Plus for Smart Rotation. Existing round history stays available. <button className={s.secondary} onClick={()=>setUnlock(true)}>View unlock options</button></p>}
 <p>{state.players.length} confirmed · Up to {Math.min(state.settings.courts,Math.floor(state.players.length/4))*4} playing · {state.players.length-Math.min(state.settings.courts,Math.floor(state.players.length/4))*4} resting</p>
 {state.status==='completed'&&<p className={s.notice}>✓ Open Play completed. Your scores are available in Results.</p>}
 {state.manager&&state.status==='published'&&<div className={s.endSession}><h3>Session controls</h3><p>Finish each round to publish its scores. End Open Play only when your entire session is finished.</p><button className={s.secondary} disabled={busy||retry||!!active||!now||Date.parse(state.starts_at)>now} onClick={finishEvent}>End Open Play</button>{!!active&&<p className={s.muted}>Finish the live round or discard its draft first.</p>}</div>}
 {state.manager&&<div className={s.actions}><button className={s.primary} disabled={!canRun||state.status!=='published'||state.settings.style==='manual'||(latest?.status==='draft'&&latest.kind!=='regular')||(!!active&&latest?.status!=='draft')} onClick={()=>prepare()}>{latest?.status==='draft'?'Regenerate rotation':'Generate next round'}</button>{latest&&['draft','live'].includes(latest.status)&&<button className={s.secondary} disabled={busy||retry||!mutable} onClick={()=>{if(window.confirm('Discard this round? It will stay in history but will not count toward statistics.'))void command('abort',{round:latest.id,version:latest.version})}}>Discard current round</button>}</div>}
 {state.status==='draft'&&<p>Publish this draft before generating rounds.</p>}
 {state.rounds.length>0&&<label>Round history<select aria-label="Round history" value={round?.id??''} onChange={e=>setView(e.target.value)}>{state.rounds.map(r=><option key={r.id} value={r.id}>Round {r.number} · {r.kind} · {r.status}</option>)}</select></label>}
 {round&&<><div className={s.roundHeading}><h3>Round {round.number} <small>{round.kind==='regular'?'':round.kind}</small></h3><span className={s.badge}>{round.status}</span></div>
 {round.status==='live'&&round.settings.round_type==='timed'&&<p className={s.timer} role="timer">{left>0?`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`:'Time’s up—finish the current rally, then complete the round.'}</p>}
 {own&&round.status!=='aborted'&&<div className={s.own}><span className={s.kicker}>YOUR ASSIGNMENT</span><h3>{own.court?`You’re playing · Court ${own.court}`:'Rest round'}</h3><p>{own.court?`Partner: ${round.assignments.filter(a=>a.court===own.court&&a.team===own.team&&a.player_id!==own.player_id).map(a=>a.display_name).join(', ')}`:'Regular rotation gives resting players priority when games played are equal.'}</p>{own.court>0&&<p>Opponents: {round.assignments.filter(a=>a.court===own.court&&a.team!==own.team).map(a=>a.display_name).join(' + ')}</p>}</div>}
 <div className={s.courts}>{round.matches.map(m=><article className={s.court} key={m.court}><span className={s.kicker}>COURT {m.court}</span>{[1,2].map(team=><div className={s.team} key={team}><div>{round.assignments.filter(a=>a.court===m.court&&a.team===team).map(a=><strong key={a.player_id}>{a.display_name}</strong>)}</div><b>{(team===1?m.a:m.b)??'—'}</b></div>)}{state.manager&&['live','completed'].includes(round.status)&&mutable&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void command('score',{round:round.id,version:round.version,scores:[{court:m.court,a:Number(f.get('a')),b:Number(f.get('b'))}]})}}><div className={s.row}><label>Team A score<input name="a" aria-label={`Court ${m.court} Team A score`} type="number" required min={0} max={199} defaultValue={m.a??''}/></label><label>Team B score<input name="b" aria-label={`Court ${m.court} Team B score`} type="number" required min={0} max={199} defaultValue={m.b??''}/></label></div><button className={s.secondary} disabled={busy||retry}>Save court {m.court} score</button></form>}</article>)}</div>
 <div className={s.rest}><span className={s.kicker}>RESTING THIS ROUND</span><p>{round.assignments.filter(a=>!a.court).map(a=>a.display_name).join(' · ')||'Everyone is playing.'}</p></div>
 {state.manager&&round.id===latest?.id&&round.status==='draft'&&<><div className={s.row}><label>Swap player<select aria-label="Swap player" value={swapA} onChange={e=>setSwapA(e.target.value)}><option value="">Choose player</option>{round.assignments.map(a=><option key={a.player_id} value={a.player_id}>{a.display_name} · {a.court?`Court ${a.court}`:'Rest'}</option>)}</select></label><label>With player<select aria-label="With player" value={swapB} onChange={e=>setSwapB(e.target.value)}><option value="">Choose player</option>{round.assignments.map(a=><option key={a.player_id} value={a.player_id}>{a.display_name} · {a.court?`Court ${a.court}`:'Rest'}</option>)}</select></label></div><div className={s.actions}><button className={s.secondary} disabled={!canRun||!swapA||!swapB||swapA===swapB} onClick={()=>{const a=round.assignments.find(a=>a.player_id===swapA)!,b=round.assignments.find(a=>a.player_id===swapB)!;void prepare(round.kind,round.assignments.map(x=>x.player_id===a.player_id?{...x,court:b.court,team:b.team}:x.player_id===b.player_id?{...x,court:a.court,team:a.team}:x))}}>Swap assignments</button><button className={s.primary} disabled={!canRun} onClick={()=>command('start',{round:round.id,version:round.version})}>Start round</button></div><p className={s.muted}>Review or swap players before starting. Rounds can start during the scheduled game time.</p></>}
 {state.manager&&round.status==='live'&&<button className={s.primary} disabled={busy||retry||!mutable} onClick={()=>command('complete',{round:round.id,version:round.version})}>Finish Round</button>}
 {round.kind==='final'&&round.status==='completed'&&round.matches[0]?.a!=null&&round.matches[0]?.b!=null&&<div className={s.own}><span className={s.kicker}>CHAMPIONS</span><h3>{round.assignments.filter(a=>a.court===1&&a.team===(round.matches[0].a!>round.matches[0].b!?1:2)).map(a=>a.display_name).join(' + ')}</h3></div>}
 </>}
 {state.settings.style==='competitive'||state.rounds.some(r=>r.settings.style==='competitive')?<><h3>Individual leaderboard</h3><p className={s.muted}>Completed regular rounds · Wins, point difference, then points for. Equal totals share a rank.</p><div className={s.tableScroll}><table><thead><tr><th>Rank</th><th>Player</th><th>GP</th><th>W</th><th>L</th><th>D</th><th>PF</th><th>PA</th><th>+/−</th></tr></thead><tbody>{standings.map(p=><tr key={p.id}><td>{p.rank}</td><td>{p.name}</td><td>{p.games}</td><td>{p.wins}</td><td>{p.losses}</td><td>{p.draws}</td><td>{p.pf}</td><td>{p.pa}</td><td>{p.pf-p.pa}</td></tr>)}</tbody></table></div></>:<><h3>Social court time</h3><div className={s.tableScroll}><table><thead><tr><th>Player</th><th>Played</th><th>Rested</th><th>Minutes*</th><th>Partners</th><th>Opponents</th></tr></thead><tbody>{[...(history?.stats.values()??[])].map(p=><tr key={p.id}><td>{p.name}</td><td>{p.games}</td><td>{p.rests}</td><td>{Math.round(p.minutes)}</td><td>{p.partners.size}</td><td>{p.opponents.size}</td></tr>)}</tbody></table></div><p className={s.muted}>*Approximate court time from round start to completion.</p></>}
 {state.manager&&state.settings.style==='competitive'&&<details><summary>Optional championship</summary><p>Top 4: #1 + #4 vs #2 + #3. Top 8: two semifinals, then the winning teams play the final. Championship rounds do not change regular standings. Tied seeds use a stable order; swap players before starting if you use a tiebreak.</p><p>Championship uses the configured target, win-by and score cap. No championship is required.</p><div className={s.actions}><button className={s.secondary} disabled={!canRun||!!active} onClick={()=>championship(4)}>Create Top 4 final</button><button className={s.secondary} disabled={!canRun||!!active} onClick={()=>championship(8)}>Create Top 8 semifinals</button>{latest?.kind==='semifinal'&&latest.status==='completed'&&<button className={s.primary} disabled={!canRun} onClick={()=>{try{void prepare('final',finalLayout(state.players,latest))}catch(e){setError(paymentError(e))}}}>Create championship final</button>}</div></details>}
 </>}
 <dialog ref={modal} className={s.dialog} onCancel={e=>e.stopPropagation()} onClose={e=>{e.stopPropagation();setUnlock(false)}} aria-label="Unlock Smart Rotation"><span className={s.kicker}>HOST SMARTER</span><h2>Unlock Smart Rotation</h2><p>Social: fair court time and rotating partners.<br/>Competitive: individual scores, rankings and an optional championship.</p><div className={s.actions}><Link className={s.primary} target="_blank" href={`/plus?game=${eventId}`} onClick={()=>setUnlock(false)}>Unlock this game · ₱39 ↗</Link><Link className={s.secondary} target="_blank" href="/plus" onClick={()=>setUnlock(false)}>Openly Plus · ₱399/month ↗</Link><button className={s.secondary} onClick={()=>setUnlock(false)}>Continue with Free</button></div><p>After admin approval, refresh rotation. The ₱39 unlock does not remove Free’s daily hosting limit.</p></dialog>
 </section>
}
function Config({settings,locked,busy,onUnlock,onSave}:{settings:RotationSettings;locked:boolean;busy:boolean;onUnlock:()=>void;onSave:(p:Record<string,unknown>)=>Promise<void>}){
 const [style,setStyle]=useState(settings.style)
 if(settings.version>0)return <section className={s.config}><div className={s.heading}><h3>{settings.style==='manual'?'Manual Play':settings.style==='social'?'Social':'Competitive'} <small>✓ Saved</small></h3><PlayStyleHelp style={settings.style}/></div><p>{settings.courts} court{settings.courts===1?'':'s'} · {settings.round_type==='timed'?`${settings.minutes} minutes per round`:`Play to ${settings.target} · Win by ${settings.win_by}`}{settings.score_cap?` · Cap ${settings.score_cap}`:''}</p><p className={s.muted}>Locked for this session.</p></section>
 return <form className={s.config} onSubmit={e=>{e.preventDefault();if(!window.confirm('Save and lock this play style for the session? These settings cannot be changed afterward.'))return;const f=new FormData(e.currentTarget);void onSave({version:settings.version,style,courts:Number(f.get('courts')),round_type:f.get('round_type'),minutes:Number(f.get('minutes')),target:Number(f.get('target')),win_by:Number(f.get('win_by')),score_cap:f.get('score_cap')?Number(f.get('score_cap')):null})}}><h3>Play style</h3><div className={s.styles}>{(['manual','social','competitive'] as const).map(v=><div key={v} className={s.styleOption}><button className={s.styleSelect} type="button" aria-pressed={style===v} disabled={busy} onClick={()=>{if(v!=='manual'&&locked)onUnlock();else setStyle(v)}}><strong>{v==='manual'?'Manual Play':v==='social'?'Social':'Competitive'}</strong><small>{v==='manual'?'FREE · You manage play':v==='social'?'PLUS · Fair rotation':'PLUS · Scores & rankings'}</small></button><PlayStyleHelp style={v}/></div>)}</div><fieldset disabled={busy}><div className={s.row}><label>Courts<input name="courts" type="number" min={1} max={20} required defaultValue={settings.courts}/></label><label>Round type<select aria-label="Round type" name="round_type" defaultValue={settings.round_type}><option value="timed">Timed</option><option value="score">Score based</option></select></label><label>Minutes per round<input name="minutes" type="number" min={1} max={180} required defaultValue={settings.minutes}/></label></div><div className={s.row}><label>Play to<select aria-label="Play to" name="target" defaultValue={settings.target}>{[7,11,15,21].map(n=><option key={n}>{n}</option>)}</select></label><label>Win by<select aria-label="Win by" name="win_by" defaultValue={settings.win_by}><option>1</option><option>2</option></select></label><label>Score cap (optional)<input name="score_cap" type="number" min={7} max={199} defaultValue={settings.score_cap??''}/></label></div><button className={s.primary}>Save play style</button></fieldset><p className={s.muted}>Saving locks these settings for this session. Timed Social scores are optional; Competitive rounds require scores.</p></form>
}
