'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import {paymentError} from './PlatformImage'
import s from './rotation.module.css'
type Round={number:number;kind:string;status:string;courts:{court:number;a:number|null;b:number|null;team_a:string[];team_b:string[]}[];resting:string[]}
type Data={current_rounds:Round[];waiting:string[];is_live:boolean;status:string;summary:string|null;current_round:Round|null;results:Round[];result_count:number}
export default function SpectatorGame({eventId,publicId,mode}:{eventId?:string;publicId?:string;mode:'rotation'|'results'}){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState(0),[version,setVersion]=useState(0)
 useEffect(()=>{let active=true;async function load(){try{const r=await (publicId?createClient().rpc('openly_spectator_public_game',{p_public:publicId,p_page:page}):createClient().rpc('openly_spectator_game',{p_event:eventId,p_page:page}));if(r.error)throw r.error;if(active){setData(r.data);setError('')}}catch(e){if(active)setError(paymentError(e))}finally{if(active)setLoading(false)}}void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},10000);return()=>{active=false;clearInterval(timer)}},[eventId,publicId,page,version])
 return <section className={s.shell} aria-label={mode==='rotation'?'Live court assignments':'Public game results'}><div className={s.heading}><h2>{mode==='rotation'?'On court now':'Game results'}</h2><button className={s.secondary} onClick={()=>setVersion(v=>v+1)}>Refresh {mode==='rotation'?'courts':'results'}</button></div>{error&&<p className={s.error} role="alert">{error}</p>}{loading?<p>Loading game updates…</p>:!data?<p>This game is not available for public viewing.</p>:mode==='rotation'?<>{data.is_live&&<p className={s.notice}>● Live Open Play</p>}{data.current_rounds?.length?<>{data.current_rounds.map(r=><RoundView key={r.number} round={r}/>)}</>:<p>{data.is_live?'No round is running right now. The host may be organizing play manually or preparing the next round.':'Live court assignments appear when the host starts a round during the scheduled game time.'}</p>}<div className={s.rest}><h3>Waiting / Resting</h3><p>{data.waiting?.join(' · ')||'No players waiting.'}</p></div></>:<><div className={s.rest}><p style={{whiteSpace:'pre-wrap'}}>{data.summary||'No host recap posted yet.'}</p></div><h3>Completed rounds</h3>{data.results.length?data.results.map(r=><RoundView key={r.number} round={r}/>):<p>No completed rounds yet.</p>}{data.result_count>20&&<div className={s.actions}><button className={s.secondary} disabled={page===0} onClick={()=>{setLoading(true);setPage(p=>p-1)}}>Previous results</button><span>Page {page+1} of {Math.ceil(data.result_count/20)}</span><button className={s.secondary} disabled={(page+1)*20>=data.result_count} onClick={()=>{setLoading(true);setPage(p=>p+1)}}>Next results</button></div>}</>}<p className={s.muted}>Read-only game updates · Refreshes every 10 seconds</p></section>
}
function RoundView({round}:{round:Round}){return <article><h3>Round {round.number}{round.kind!=='regular'?` · ${round.kind}`:''}</h3><div className={s.courts}>{round.courts.map(c=><div className={s.court} key={c.court}><span className={s.kicker}>COURT {c.court}</span><div className={s.team}><div>{c.team_a?.map((name,i)=><strong key={i}>{name}</strong>)}</div><b>{c.a??'—'}</b></div><div className={s.team}><div>{c.team_b?.map((name,i)=><strong key={i}>{name}</strong>)}</div><b>{c.b??'—'}</b></div></div>)}</div>{round.status==='live'&&round.resting.length>0&&<div className={s.rest}><span className={s.kicker}>RESTING THIS ROUND</span><p>{round.resting.join(' · ')}</p></div>}</article>}
