'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import SupportConversation from '@/app/support/SupportConversation'
import s from '@/app/components/platform.module.css'
type Thread={user_id:string;status:string;profile:{display_name:string}|null}
export default function SupportInbox(){const [rows,setRows]=useState<Thread[]>([]),[selected,setSelected]=useState<Thread|null>(null),[uid,setUid]=useState(''),[page,setPage]=useState(0),[version,setVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{let active=true;async function load(){const db=createClient(),auth=await db.auth.getUser(),r=await db.from('support_threads').select('user_id,status,profile:profiles!user_id(display_name)').order('updated_at',{ascending:false}).order('user_id').range(page*20,page*20+20);if(active){setUid(auth.data.user?.id??'');if(r.error)setError(r.error.message);else setRows((r.data??[]).map(t=>({...t,profile:Array.isArray(t.profile)?t.profile[0]:t.profile})))}}void load();const timer=window.setInterval(()=>void load(),10000);return()=>{active=false;window.clearInterval(timer)}},[page,version])
 return <><span className={s.kicker}>OPENLY ADMIN</span><h1>Customer Support</h1>{error&&<p className={s.error} role="alert">{error}</p>}{selected&&<section className={s.card}><div className={s.receiptHeading}><h2>{selected.profile?.display_name??'Customer'}</h2><button className={s.secondary} onClick={()=>setSelected(null)}>Close conversation</button></div><SupportConversation key={selected.user_id} uid={uid} thread={selected.user_id}/><button className={s.secondary} disabled={busy} onClick={async()=>{setBusy(true);const r=await createClient().rpc('openly_support_resolve',{p_thread:selected.user_id,p_resolved:true});setBusy(false);if(r.error)setError(r.error.message);else{setSelected(null);setVersion(v=>v+1)}}}>Mark resolved</button></section>}<div className={s.tableList}>{rows.slice(0,20).map(t=><article className={s.card} key={t.user_id}><div className={s.receiptHeading}><h3>{t.profile?.display_name??'Customer'}</h3><span className={s.pill}>{t.status}</span></div><button className={s.secondary} onClick={()=>setSelected(t)}>Open conversation</button></article>)}</div>{!rows.length&&<p className={s.empty}>No support conversations yet.</p>}<div className={s.actions}><button className={s.secondary} disabled={page===0} onClick={()=>setPage(v=>v-1)}>Previous</button><span>Page {page+1}</span><button className={s.secondary} disabled={rows.length<=20} onClick={()=>setPage(v=>v+1)}>Next</button></div></>}
