'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import PlatformImage,{paymentError} from '@/app/components/PlatformImage'
import OrderPayment from './OrderPayment'
import {paymentMethodName,type Order,type PaymentMethod} from './types'
import s from '@/app/components/platform.module.css'
import p from './pricing.module.css'
import PlanIcon from './PlanIcon'
export default function BillingPanel({uid,initialEvent=''}:{uid:string;initialEvent?:string}){
 const [orders,setOrders]=useState<Order[]>([]),[games,setGames]=useState<{id:string;title:string}[]>([]),[unlocked,setUnlocked]=useState<string[]>([]),[selected,setSelected]=useState(''),[event,setEvent]=useState(initialEvent)
 const [enabled,setEnabled]=useState(false),[expires,setExpires]=useState(''),[active,setActive]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0)
 const [methods,setMethods]=useState<PaymentMethod[]>([]),[method,setMethod]=useState('')
 const [checkout,setCheckout]=useState(''),dialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{if(checkout)dialog.current?.showModal();else dialog.current?.close()},[checkout])
 function openCheckout(product:string){setSelected('');setError('');setCheckout(product)}
 const request=useRef<{id:string;product:string;event:string|null;method:string}|null>(null),lock=useRef(false)
 useEffect(()=>{let live=true;async function load(){try{const db=createClient();const [settings,o,pending,g,sub,features]=await Promise.all([
 db.from('platform_payment_methods').select('*').eq('enabled',true).order('provider'),db.from('platform_orders').select('*').eq('host_id',uid).order('created_at',{ascending:false}).limit(100),db.from('platform_orders').select('*').eq('host_id',uid).in('status',['awaiting_payment','pending_review','rejected']),
 db.from('open_plays').select('id,title').eq('host_id',uid).in('status',['draft','published']).gt('ends_at',new Date().toISOString()).order('starts_at').limit(100),db.from('host_subscriptions').select('current_period_start,current_period_end,status').eq('host_id',uid).eq('status','active').gt('current_period_end',new Date().toISOString()).order('current_period_end',{ascending:false}),db.from('premium_feature_purchases').select('open_play_id').eq('host_id',uid).eq('feature','smart_rotation')])
 for(const r of [settings,o,pending,g,sub,features])if(r.error)throw r.error
 if(live){const available=settings.data??[];setMethods(available);setEnabled(available.length>0);setMethod(current=>available.some(m=>m.provider===current)?current:available.find(m=>m.provider==='paymongo')?.provider??available[0]?.provider??'');setOrders([...new Map([...(pending.data??[]),...(o.data??[])].map(v=>[v.id,v as Order])).values()]);setGames(g.data??[]);setExpires(sub.data?.[0]?.current_period_end??'');setActive(!!sub.data?.some(v=>new Date(v.current_period_start).getTime()<=Date.now()));setUnlocked((features.data??[]).map(v=>v.open_play_id));setReady(true)}}catch(e){if(live)setError(paymentError(e))}}void load();return()=>{live=false}},[uid,version])
 async function purchase(product:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const game=product==='smart_rotation_session'?event:null;if(product==='smart_rotation_session'&&!game)throw Error('Select your game first.');if(!method)throw Error('Choose a payment method.');if(!request.current||request.current.product!==product||request.current.event!==game||request.current.method!==method)request.current={id:crypto.randomUUID(),product,event:game,method};const r=await createClient().rpc('openly_create_platform_order',{p_request:request.current.id,p_product:product,p_event:game,p_method:method});if(r.error)throw r.error;setSelected(r.data);request.current=null;setVersion(v=>v+1)}catch(e){setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 const order=orders.find(o=>o.id===selected)
 return <><span className={s.kicker}>HOST SMARTER</span><h1>Openly Plus</h1><p>Free hosting stays free. Plus belongs to the host; players never need a subscription.</p>
 {error&&<p className={s.error} role="alert">{error}</p>}<div className={s.actions}><Link className={s.secondary} href="/host">Continue with Free</Link><button className={s.secondary} onClick={()=>{setError('');setVersion(v=>v+1)}}>Refresh status</button></div>

 {!enabled&&ready&&<p className={s.notice}>Purchases are paused until an admin enables a receiving account in Payment settings. You can keep hosting free or <Link href="/support">message support</Link>.</p>}
 <div className={p.grid}>
 <section className={p.card} aria-labelledby="free-plan"><header className={p.cardHeader}><span className={p.icon}><PlanIcon name="layers"/></span><div><span className={p.kicker}>ALWAYS AVAILABLE</span><h2 id="free-plan">Free hosting</h2><p>Get started. Bring people together.</p></div></header><div className={p.price}>₱0</div><p className={p.description}>Publish up to 3 Open Plays per Philippine day. Save drafts, set fees, accept players and share your games.</p><footer className={p.footer}><Link className={p.primary} href="/host">Create an Open Play <PlanIcon name="arrow"/></Link></footer></section>
 <section className={p.card} aria-labelledby="session-plan"><header className={p.cardHeader}><span className={p.icon}><PlanIcon name="ticket"/></span><div><span className={p.kicker}>ONE GAME</span><h2 id="session-plan">Session unlock</h2><p>Unlock more possibilities.</p></div></header><div className={p.price}>₱39<small>/ session</small></div><p className={p.description}>Smart Rotation for one saved Open Play. The unlock stays with that game and does not remove the Free hosting limit.</p><footer className={p.footer}>{active?<div className={p.included}><PlanIcon name="check"/><span>Included with your Openly Plus</span></div>:<button className={p.primary} disabled={!ready||busy||!enabled} onClick={()=>openCheckout('smart_rotation_session')}>Unlock for ₱39 <PlanIcon name="arrow"/></button>}</footer></section>
 <section className={`${p.card} ${p.featured}`} aria-labelledby="plus-plan"><span className={p.ribbon}>FOR REGULAR HOSTS</span><header className={p.cardHeader}><span className={p.icon}><PlanIcon name="crown"/></span><div><span className={p.kicker}>YOUR HOST TOOLS</span><h2 id="plus-plan">Openly Plus</h2><p>More games. A stronger community.</p></div></header><div className={p.price}>₱399<small>/ month</small></div><p className={p.description}>Unlimited daily hosting, Social rotation, Competitive scoring and optional championship. One calendar month from approval; early renewal extends your paid-through date.</p><footer className={p.footer}>{active&&<div className={p.member}><PlanIcon name="check"/><div><strong>✓ You’re already Plus+</strong><span>Active until {new Date(expires).toLocaleDateString('en-PH',{timeZone:'Asia/Manila',year:'numeric',month:'long',day:'numeric'})}</span></div></div>}<button className={active?p.outline:p.primary} disabled={!ready||busy||!enabled} onClick={()=>openCheckout('openly_plus_monthly')}>{active?'Extend subscription':'Get Openly Plus'} <PlanIcon name="arrow"/></button></footer></section>
 </div>
 <dialog ref={dialog} className={`${s.dialog} ${s.checkoutDialog}`} aria-labelledby="checkout-title" onCancel={e=>{if(busy)e.preventDefault()}} onClose={()=>{if(!dialog.current?.open){setCheckout('');setSelected('')}}}>
 <button className={s.close} aria-label="Close checkout" disabled={busy} onClick={()=>setCheckout('')}>×</button>
 <span className={s.kicker}>OPENLY HOST TOOLS</span><h2 id="checkout-title">{checkout==='smart_rotation_session'?'Unlock one session':checkout==='history'?'Your purchase':'Openly Plus'}</h2>
 {error&&<p role="alert" className={s.error}>{error}</p>}
 {order?<><p className={s.muted}>This request uses {paymentMethodName(order.payment_snapshot.provider)}. Existing requests keep their original payment account. To switch, cancel an unpaid request first.</p><OrderPayment key={order.id} order={order} uid={uid} onRefresh={()=>setVersion(v=>v+1)}/></>:selected?<p>Loading your payment request…</p>:checkout!=='history'&&<>
 <p className={s.checkoutPrice}>{checkout==='smart_rotation_session'?'₱39 / session':'₱399 / month'}</p>
 {active&&checkout==='openly_plus_monthly'&&<p>One calendar month will be added after your current paid-through date when the admin approves your payment.</p>}
 {checkout==='smart_rotation_session'&&<label>Your Open Play<select aria-label="Your Open Play" disabled={busy} value={event} onChange={e=>setEvent(e.target.value)}><option value="">Choose a game</option>{games.map(g=><option key={g.id} value={g.id}>{g.title}{unlocked.includes(g.id)?' · Unlocked ✓':''}</option>)}</select></label>}
 {checkout==='smart_rotation_session'&&unlocked.includes(event)?<p className={s.notice}>✓ Session unlocked. You already have Smart Rotation for this game.</p>:<>
 <fieldset className={s.paymentChoice} disabled={busy}><legend>How would you like to pay?</legend><div>{methods.map(m=><label key={m.provider} className={method===m.provider?s.selectedMethod:''}><input type="radio" name="payment-method" value={m.provider} checked={method===m.provider} onChange={()=>setMethod(m.provider)}/><span>{paymentMethodName(m.provider)}</span></label>)}</div></fieldset>
 {methods.filter(m=>m.provider===method).map(m=><div key={m.provider} className={s.card}><h3>{paymentMethodName(m.provider)}</h3><p>{m.account_name}<br/>{m.account_number}</p>{m.provider==='paymongo'?<p>Pay securely on Openly’s PayMongo page using QR Ph. Continue below to create your request, then open the payment page. Return here to submit your receipt for admin verification.</p>:<PlatformImage key={m.qr_path} bucket="platform-qrs" path={m.qr_path} alt={`${paymentMethodName(m.provider)} QR preview`}/>}</div>)}
 <p className={s.muted}>Continue below before sending payment. We’ll open your payment request with the exact account details and receipt upload.</p>
 <button className={s.primary} disabled={busy||!enabled||!method||(checkout==='smart_rotation_session'&&!event)} onClick={()=>purchase(checkout)}>{busy?'Opening payment…':'Continue to payment'}</button>
 </>}
 </>}
 </dialog>
 <h2>Your purchase history</h2>{!orders.length?<p className={s.empty}>{ready?'No purchases yet.':'Loading purchases…'}</p>:<div className={s.tableList}>{orders.map(o=><article className={s.card} key={o.id}><div className={s.receiptHeading}><strong>{o.product==='openly_plus_monthly'?'Openly Plus monthly':`Session unlock${games.find(g=>g.id===o.open_play_id)?` · ${games.find(g=>g.id===o.open_play_id)?.title}`:''}`}</strong><span>₱{Number(o.amount).toFixed(2)}</span></div><p>{o.status.replaceAll('_',' ')} · {new Date(o.created_at).toLocaleDateString('en-PH',{timeZone:'Asia/Manila'})}</p><button className={s.secondary} onClick={()=>{setSelected(o.id);setError('');setCheckout('history')}}>View payment</button></article>)}</div>}<p className={s.muted}>Latest 100 purchases plus open requests. No automatic renewals or refunds.</p></>
}
