'use client'
import {useEffect,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import PlatformImage,{paymentError,uploadPlatformImage} from '@/app/components/PlatformImage'
import {validPaymongoLink,paymentMethodName,type Order,type Receipt} from './types'
import s from '@/app/components/platform.module.css'
export default function OrderPayment({order,uid,onRefresh}:{order:Order;uid:string;onRefresh:()=>void}){
 const [receipt,setReceipt]=useState<Receipt|null>(null),[reference,setReference]=useState(''),[file,setFile]=useState<File|null>(null),[path,setPath]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[cancel,setCancel]=useState(false)
 const lock=useRef(false)
 useEffect(()=>{let active=true;void createClient().from('platform_payment_receipts').select('id,object_path,payment_reference,status,rejection_reason,submitted_at').eq('order_id',order.id).order('submitted_at',{ascending:false}).limit(1).maybeSingle().then(r=>{if(active){if(r.error)setError(r.error.message);else setReceipt(r.data)}});return()=>{active=false}},[order.id,order.status])
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();onRefresh()}catch(e){setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 const canPay=['awaiting_payment','rejected'].includes(order.status),snapshot=order.payment_snapshot
 return <section className={s.card}><div className={s.receiptHeading}><h3>{order.product==='openly_plus_monthly'?'Openly Plus · one month':'Smart Rotation · one session'}</h3><span className={s.pill}>₱{Number(order.amount).toFixed(2)}</span></div><p>Purchase {order.id}</p><p className={s.notice}>{order.status==='approved'?'Approved — access recorded.':order.status==='pending_review'?'Awaiting admin verification':order.status==='rejected'?'Receipt rejected — check the reason and resubmit.':order.status==='cancelled'?'Purchase cancelled':'Pay Openly, then submit your receipt.'}</p>
 {receipt?.rejection_reason&&<p className={s.error}>{receipt.rejection_reason}</p>}{error&&<p role="alert" className={s.error}>{error}</p>}
 {canPay&&<><p><strong>{paymentMethodName(snapshot.provider)}</strong><br/>{snapshot.account_name}<br/>{snapshot.account_number}</p>{snapshot.provider==='paymongo'?<><p>1. Open PayMongo and pay the amount below.<br/>2. Return here and submit your payment receipt and transaction reference.<br/>3. Admin verifies your payment and activates access.</p>{validPaymongoLink(snapshot.payment_url)?<a className={s.primary} href={snapshot.payment_url} target="_blank" rel="noopener noreferrer">Open PayMongo payment page ↗</a>:<p role="alert" className={s.error}>Payment link unavailable. Contact support before paying.</p>}<p className={s.muted}>Opening the link does not confirm payment. Keep your PayMongo transaction reference so the admin can match it to this purchase.</p></>:<PlatformImage bucket="platform-qrs" path={snapshot.qr_path} alt="Openly payment QR for this purchase"/>}<p className={s.muted}>Pay exactly ₱{Number(order.amount).toFixed(2)}. This pays Openly for host tools, not your game’s joining fee.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{let objectPath=path;if(!objectPath){if(!file)throw Error('Choose a payment receipt.');objectPath=await uploadPlatformImage('platform-proofs',`${uid}/${order.id}`,file);setPath(objectPath)}const r=await createClient().rpc('openly_submit_platform_receipt',{p_order:order.id,p_path:objectPath,p_reference:reference});if(r.error)throw r.error;setFile(null);setPath('');setReference('')})}}><label>Transaction reference<input required minLength={3} maxLength={120} value={reference} disabled={busy} onChange={e=>setReference(e.target.value)}/></label><label>Payment receipt<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||!!path} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className={s.primary} disabled={busy||(!file&&!path)}>{busy?'Submitting…':path?'Retry receipt submission':'Submit receipt'}</button></form><details><summary>Cancel this request</summary><p className={s.muted}>Cancellation does not refund money already sent. Contact the admin if you have paid.</p><label><input type="checkbox" checked={cancel} onChange={e=>setCancel(e.target.checked)}/>I understand this does not issue a refund.</label><button className={s.secondary} disabled={busy||!cancel} onClick={()=>run(async()=>{const r=await createClient().rpc('openly_cancel_platform_order',{p_order:order.id});if(r.error)throw r.error})}>Cancel request</button></details></>}
 {receipt&&<details><summary>Latest submitted receipt</summary><p>Reference: {receipt.payment_reference}</p><PlatformImage bucket="platform-proofs" path={receipt.object_path} alt="Your Openly payment receipt"/></details>}<button className={s.secondary} disabled={busy} onClick={onRefresh}>Refresh purchase</button></section>
}
