import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata: Metadata = {
  title: "Privacy Policy | Openly",
  description: "How Openly handles account, game, payment and support information.",
  alternates: { canonical: "https://playopenly.com/privacy" },
};

const sections = [
  ["1. Who we are", "Openly is a platform for discovering, hosting and joining pickleball Open Plays at playopenly.com. This notice explains how Openly handles personal information. For privacy questions or requests, contact openly.rc@gmail.com."],
  ["2. Information we collect", "When you sign in with Google, we receive your Google account identifier, email address, name and profile picture when provided by Google. We use these details to authenticate you and create or maintain your Openly profile. This sign-in does not give us your Google password or access to your Gmail messages, contacts or Drive files.", "We also process information you submit or generate through Openly: profile details, hosted games and locations, join requests, participant status, rotation and results records, chat messages, support messages, and payment references or uploaded receipts. Our infrastructure providers may process technical information such as IP addresses, browser information and request logs to deliver and protect the service."],
  ["3. How we use information", "We use information to operate accounts, display games and participants, manage requests and host decisions, provide rotation and results tools, verify payments and premium access, respond to support requests, and investigate misuse. We process information as needed to provide the service you request, meet applicable obligations, and pursue legitimate operational and security purposes where permitted. Where consent is required, we request it and you may withdraw it."],
  ["4. What other people can see", "Game details, host identity, participant names or display names, profile pictures, participation status, results and current rotation information may be visible to other users and visitors who are not signed in. Pending participants may be visible before confirmation. Do not put private contact details or sensitive information in public profile or game fields.", "Game chat messages are shared with people granted access to that chat. Hosts can review information needed to manage their game and verify participant payments. Openly administrators can review premium payment submissions and support requests. Do not upload passwords, full card details or unrelated identity documents; redact unnecessary receipt information."],
  ["5. Providers and payments", "Openly uses Google for sign-in, Supabase for authentication and data storage, and Vercel for website hosting. These providers process information needed to provide their services and may process it outside the Philippines. We use applicable safeguards for these service arrangements.", "If you choose a PayMongo payment link, you leave Openly to pay on PayMongo’s hosted page, subject to its privacy notice and terms. Openly processes the payment references, receipts and verification records submitted or made available to it; it does not need your card PIN or online banking password. Payments to individual hosts are handled through the host’s selected payment arrangements.", "We do not sell your personal information or use Google account data for targeted advertising. Information may also be disclosed when legally required or reasonably necessary to investigate fraud and protect users."],
  ["6. Cookies, storage and security", "Authentication cookies or browser storage are used to maintain sign-in and necessary application state. Blocking or clearing them may sign you out or prevent features from working. We use access controls and other reasonable safeguards, but no online system can guarantee absolute security."],
  ["7. Retention and deletion", "We retain information for as long as needed to operate your account and the related games, handle support or disputes, prevent abuse, and meet applicable recordkeeping requirements. Retention depends on the type and purpose of the record. When it is no longer needed, information should be deleted or anonymized; backups may retain copies until their normal expiry.", "To request account deletion, email openly.rc@gmail.com from your registered email address. We may verify ownership before acting. Some transaction, dispute or security records may need to be retained where legally required or justified; we will explain relevant limitations. Removing Google access alone does not delete information already stored by Openly."],
  ["8. Your choices and rights", "Subject to applicable law, you may request access to, correction, deletion or blocking of your information, object to processing, withdraw consent, and request portability where applicable. Contact openly.rc@gmail.com to exercise these rights or raise a concern. You may also raise a complaint with the Philippine National Privacy Commission. You can revoke Openly’s access through your Google Account’s third-party connections settings."],
  ["9. Young users and updates", "If you are under 18, involve a parent or guardian before providing personal information, paying or participating. If a child’s information was submitted without appropriate authorization, contact us so we can review it. We may update this policy as Openly changes, update the date below, and provide additional notice or seek consent where required."],
];

export default function PrivacyPage() {
  return <main className={styles.page}><div className={styles.wrap}>
    <nav className={styles.nav} aria-label="Page navigation"><Link href="/" className={styles.brand}>openly<span>.</span></Link><Link href="/">Back to Discover</Link></nav>
    <p className={styles.eyebrow}>Your information, explained</p><h1>Privacy Policy</h1>
    <p className={styles.intro}>Last updated: September 17, 2026<br />How we handle information while bringing your court crew together.</p>
    <article className={styles.article}>{sections.map(([title, ...paragraphs]) => <section key={title}><h2>{title}</h2>{paragraphs.map(p => <p key={p}>{p}</p>)}</section>)}</article>
    <footer className={styles.footer}><Link href="/terms">Terms of Service</Link><a href="mailto:openly.rc@gmail.com">Contact Openly</a></footer>
  </div></main>;
}
