'use client'
import {useEffect,useRef,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import PlatformImage,{paymentError} from '@/app/components/PlatformImage'
import {validPaymongoLink,paymentMethodName,type Order,type Receipt} from '@/app/plus/types'
import s from '@/app/components/platform.module.css'
export type ReviewOrder=Order&{host:{display_name:string}|null;game:{title:string}|null}
const labels:Record<string,string>={pending_review:'Awaiting review',approved:'Approved',rejected:'Rejected',awaiting_payment:'Awaiting payment',cancelled:'Cancelled'}
export default function PaymentReview(){
 const [orders,setOrders]=useState<ReviewOrder[]>([]),[filter,setFilter]=useState('pending_review'),[page,setPage]=useState(0),[more,setMore]=useState(false),[selected,setSelected]=useState<ReviewOrder|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0),[uid,setUid]=useState('')
 useEffect(()=>{let active=true;async function load(){setReady(false);setError('');try{const db=createClient(),auth=await db.auth.getUser();if(auth.error)throw auth.error;let query=db.from('platform_orders').select('*,host:profiles!host_id(display_name),game:open_plays!open_play_id(title)').order('created_at',{ascending:false}).order('id').range(page*20,page*20+20);if(filter!=='all')query=query.eq('status',filter);const r=await query;if(r.error)throw r.error;if(active){setUid(auth.data.user?.id??'');setOrders(r.data.slice(0,20));setMore(r.data.length>20)}}catch(e){if(active)setError(paymentError(e))}finally{if(active)setReady(true)}}void load();return()=>{active=false}},[filter,page,version])
 return <><span className={s.kicker}>OPENLY ADMIN</span><h1>Premium payments</h1><p>Check the actual transfer in your payment account before approving a receipt. Approval records the host’s premium access.</p><div className={s.paymentToolbar}><label>Payment status<select aria-label="Payment status" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);setSelected(null)}}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}<option value="all">All purchases</option></select></label><button className={s.secondary} disabled={!ready} onClick={()=>setVersion(n=>n+1)}>Refresh payments</button></div>{error&&<p role="alert" className={s.error}>{error}</p>}
 {selected&&<Review key={`${selected.id}-${version}`} order={selected} uid={uid} onClose={()=>setSelected(null)} onReviewed={()=>{setSelected(null);setVersion(n=>n+1)}}/>}
 {!ready?<p role="status">Loading payments…</p>:<><div className={s.tableList}>{orders.map(o=><article className={s.card} key={o.id}><div className={s.receiptHeading}><h3>{o.host?.display_name??'Host'}</h3><span className={s.pill}>{labels[o.status]}</span></div><p>{o.product==='openly_plus_monthly'?'Openly Plus · one month':'Smart Rotation · one session'} · <strong>₱{Number(o.amount).toFixed(2)}</strong>{o.game&&<><br/>{o.game.title}</>}</p><p className={s.muted}>{o.id}<br/>Reference: {o.payment_reference??'Not submitted'}</p><button className={s.secondary} onClick={()=>setSelected(o)}>Review purchase</button></article>)}</div>{!orders.length&&<p className={s.empty}>No purchases in this view.</p>}<div className={s.actions}><button className={s.secondary} disabled={page===0} onClick={()=>{setSelected(null);setPage(n=>n-1)}}>Previous</button><span>Page {page+1}</span><button className={s.secondary} disabled={!more} onClick={()=>{setSelected(null);setPage(n=>n+1)}}>Next</button></div></>}
 </>
}
export function Review({order,uid,onClose,onReviewed}:{order:ReviewOrder;uid:string;onClose:()=>void;onReviewed:()=>void}){
 const [receipts,setReceipts]=useState<Receipt[]>([]),[ready,setReady]=useState(false),[verified,setVerified]=useState(false),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0);const lock=useRef(false)
 useEffect(()=>{let active=true;async function load(){try{const r=await createClient().from('platform_payment_receipts').select('id,object_path,payment_reference,status,rejection_reason,submitted_at').eq('order_id',order.id).order('submitted_at',{ascending:false});if(r.error)throw r.error;if(active)setReceipts(r.data)}catch(e){if(active)setError(paymentError(e))}finally{if(active)setReady(true)}}void load();return()=>{active=false}},[order.id,version])
 const pending=receipts.find(r=>r.status==='pending_review'),own=order.host_id===uid
 async function review(approve:boolean){if(lock.current||!pending)return;lock.current=true;setBusy(true);setError('');try{const r=await createClient().rpc('openly_review_platform_receipt',{p_receipt:pending.id,p_approve:approve,p_reason:approve?null:reason});if(r.error)throw r.error;onReviewed()}catch(e){setError(paymentError(e))}finally{lock.current=false;setBusy(false)}}
 return <section className={s.card} aria-label="Review premium payment"><div className={s.receiptHeading}><h2>Payment from {order.host?.display_name??'host'}</h2><button className={s.secondary} disabled={busy} onClick={onClose}>Close review</button></div><p><strong>₱{Number(order.amount).toFixed(2)}</strong> · {order.product==='openly_plus_monthly'?'One month of Openly Plus':`Smart Rotation for ${order.game?.title??'this game'}`}</p><p className={s.muted}>Paid to: {order.payment_snapshot.account_name} · {order.payment_snapshot.account_number} · {paymentMethodName(order.payment_snapshot.provider)}</p>{order.payment_snapshot.provider==='paymongo'&&<p className={s.notice}>Verify the successful payment, amount and unique transaction reference in your PayMongo dashboard before approving. A screenshot alone does not verify receipt of money. {validPaymongoLink(order.payment_snapshot.payment_url)&&<a href={order.payment_snapshot.payment_url} target="_blank" rel="noopener noreferrer">Original payment page ↗</a>}</p>}{error&&<p role="alert" className={s.error}>{error}</p>}{!ready?<p>Loading receipts…</p>:!receipts.length?<p>No receipt submitted yet.</p>:receipts.map(r=><details key={r.id} open={r.status==='pending_review'}><summary>{labels[r.status]} · {r.payment_reference}</summary><p>Reference: <strong>{r.payment_reference}</strong></p><PlatformImage bucket="platform-proofs" path={r.object_path} alt={`Receipt ${r.payment_reference}`}/>{r.rejection_reason&&<p className={s.error}>{r.rejection_reason}</p>}</details>)}
 {pending&&<>{own?<p className={s.notice}>Another administrator must review your own payment.</p>:<><label><input type="checkbox" checked={verified} disabled={busy} onChange={e=>setVerified(e.target.checked)}/>I verified the amount and transaction reference in the receiving account.</label><button className={s.primary} disabled={busy||!verified} onClick={()=>void review(true)}>{busy?'Saving…':'Approve & activate access'}</button><label>Reason for rejection<textarea maxLength={1000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)} placeholder="Explain what the host needs to correct"/></label><button className={s.secondary} disabled={busy||!reason.trim()} onClick={()=>void review(false)}>Reject receipt</button></>}</>}
 <div className={s.actions}><button className={s.secondary} disabled={busy} onClick={()=>{setError('');setReady(false);setVersion(n=>n+1)}}>Reload receipts</button></div></section>
}
